### ISSUE TITLE
[Rector] Parallel testing

### ISSUE THREAD

**Issue by azdanov** [rectorphp/rector#1179]
Would it be faster using https://github.com/paratestphp/paratest?

I've had memory issues with `phpunit`, but no problems with `paratest`, since it starts several processes.

**Comment by TomasVotruba** [comment]
I think before/after would tell us

**Comment by azdanov** [comment]
What interested me more is `memory_limit`.
Before I had to set it really high (`2048M`) for all tests, now even `128M` works.

Here's my machine's benchmark (_2nd run_):

```sh
time vendor/bin/paratest

# 23.87 real        55.09 user        26.33 sys

time vendor/bin/phpunit

# 73.16 real        34.33 user        37.32 sys
```

Probably need more benchmarking. Especially CI.

**Comment by mrpixeldream** [comment]
I made a quick comparison on my local system (MacBook Pro from 2017, i7, 16 GB RAM) against the current `master`:  
Just PHPUnit:  
`./vendor/bin/phpunit  157.19s user 44.42s system 94% cpu 3:32.69 total`

With paratest:  
`./vendor/bin/paratest -p2  221.43s user 65.32s system 185% cpu 2:34.39 total`

I tested with `-p2` because Travis builds in an environment with two cores as well, according to the documentation: https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system 

Quite a performance benefit I think, reducing the build time by one minute. Also it seems to mitigate memory issues that arise when running everything in one process so I see nothing that goes against implementing that into the build chain 👍

**Comment by azdanov** [comment]
I'll try to do a better benchmark with https://github.com/sharkdp/hyperfine.

**Comment by azdanov** [comment]
For some reason paratest is worse on the first run.

```sh
hyperfine --warmup 3 -i vendor/bin/paratest

Benchmark #1: vendor/bin/paratest
  Time (mean ± σ):     26.575 s ±  5.426 s    [User: 55.531 s, System: 27.170 s]
  Range (min … max):   22.205 s … 40.887 s    10 runs
```

```sh
hyperfine --warmup 3 -i vendor/bin/phpunit

Benchmark #1: vendor/bin/phpunit
  Time (mean ± σ):     11.626 s ±  0.384 s    [User: 5.769 s, System: 6.066 s]
  Range (min … max):   11.084 s … 12.133 s    10 runs
```

**Comment by mrpixeldream** [comment]
I am pretty sure PHPUnit caches results and uses them if no files/tests were changed. Maybe that's the issue and when using paratest, it can't detect the cached results or something along those lines. I can not imagine that the whole test suite passes in 12 seconds.

**Comment by azdanov** [comment]
It does make sense. Since PHPUnit test list doesn't change. But Paratest is probably selecting tests in an arbitrary fashion.

**Comment by mrpixeldream** [comment]
You could try to delete all cache files (most likely just one in the root directory of your project) and then benchmark again using `--do-not-cache-result`. You can also pass that argument through to PHPUnit when using paratest.

**Comment by azdanov** [comment]
Tried again, somewhat same results. PHPUnit probably messes something up here. 🤷‍♂️ 

```sh
Benchmark #1: vendor/bin/paratest --passthru='--do-not-cache-result'
  Time (mean ± σ):     22.225 s ±  1.296 s    [User: 53.722 s, System: 24.078 s]
  Range (min … max):   20.730 s … 23.680 s    10 runs

Benchmark #1: vendor/bin/phpunit --do-not-cache-result
  Time (mean ± σ):     11.092 s ±  0.132 s    [User: 5.596 s, System: 5.725 s]
  Range (min … max):   10.974 s … 11.355 s    10 runs
```

**Comment by TomasVotruba** [comment]
If I read it correctly, all tests show that paratest is 2-times slower.

Closing as time on first run is very important on CI, where are many "first runs".
