### ISSUE TITLE
Documented way to use docker do not work

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#1394]
I had to launch it using this :
```
docker run -v $(pwd):/project rector/rector:latest php /rector/bin/rector  process /rector/src --level symfony34 --dry-run
```
Instead of 
```
docker run -v $(pwd):/project rector/rector:latest process /rector/src --level symfony34 --dry-run
```

**Comment by TomasVotruba** [comment]
Ping @JanMikes

**Comment by JanMikes** [comment]
Hi @vasilvestre could you please try running `docker pull rector/rector` and confirm it still does not work?

**Comment by vasilvestre** [comment]
@JanMikes I will be back at work this monday :)

**Comment by JanMikes** [comment]
Sure, just let me know if it fixed your issue or we will investigate further 😉

**Comment by vasilvestre** [comment]
It worked ! @JanMikes  thank you

I've research if there was a flag to pull and.. it's coming soon : https://github.com/docker/cli/pull/1498
You may keep an eye on it to update doc :D

**Comment by JanMikes** [comment]
@vasilvestre thank you, i will update docs very soon, recently i have updated rector's docker image build behavior and when next stable version of rector will get tagged, the same tag will appear in docker hub, so you can use specific version of rector in docker instead of always using latest (and possible unstable)
