### ISSUE TITLE
StringClassNameToClassConstantRector transforms strings into namespaces when should not do it

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#1539]
```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -188,7 +188,7 @@
         }

         if (null !== $exception && $event->isDebug()) {
-            $this->getLogger()->error('{message}', ['exception' => $exception, 'message' => $message]);
+            $this->getLogger()->error('{message}', [\exception::class => $exception, 'message' => $message]);
         }

         $this->getConsoleNotificationManager()->write('errorLine', $message);
    ----------- end diff -----------

    ---------- begin diff ----------
--- Original
+++ New
@@ -218,7 +218,7 @@
             $options = $reflected->invoke($s3Adapter, 'dummy');

             $bucket    = $options['Bucket'];
-            $directory = $options['directory'];
+            $directory = $options[\directory::class];
         }

         return 'S3://' . $bucket . '/' . $directory . '/';
    ----------- end diff -----------

Applied rectors:

 * Rector\Php\Rector\String_\StringClassNameToClassConstantRector
```

Assuming both classes exist (`\Exception` and `\Directory`), the rector anyway transforms them wrongly using all lowercase letters.

But the main problem here is that both `exception` and `directory` are keys of an array, so should not be transformed at all.

**Comment by TomasVotruba** [comment]
Thanks for reporting.

There are many approaches with differnt -/+:

- 1. ignore upper/lower case of clases (current approach) - it will replace typoed classes, but also strings sometimes, becuase "directory" is usually a string, but "Directory" might be a class

- 2. skip simple words like "exception", "directory" and "error", because people tend to use them as a string

Maybe we could make it case sensitive and upper/lower case mistakes delegate to another fixer/rule. What do you think?

**Comment by Aerendir** [comment]
I think the second one approach is the best one: highlight such misspellings should be delegated to IDEs like PHPStorm and to static code analyzers. And I think is also the simplest approach...
