### ISSUE TITLE
Problem with classes from global namespace like \Redis or \Memcached

### ISSUE THREAD

**Issue by pawel-brzezinski** [rectorphp/rector#1547]
Hi,
I have a problem with classes from global namespace like \Redis or \Memcached. I run Rector by docker
```
docker run -v $(pwd):/project rector/rector:latest process /project/src --level symfony28 --autoload-file /project/vendor/autoload.php --dry-run
```
and I've got errors like this one:
```
"Analyze error: "Class Redis not found and could not be autoloaded.".
```
I suppose that should I point some more things than only vendor autoload?

Thanks for help!

**Comment by JanMikes** [comment]
Hi @pawel-brzezinski !

First, I will explain what the problem is - if you check [Rector's Dockerfile](https://github.com/rectorphp/rector/blob/master/Dockerfile) it is pretty simple one, without much php extensions, but default ones. That means, in Rector's docker container (`rector/rector`) there is no Redis or Memcached extensions - so class \Redis or \Memcached does really not exist inside of it.

I have solved it on other project, where we had missing like 10 php extensions and i wanted to use rector (and it was failing for example on missing \Imagick class) this way - i created locally Dockerfile which extended rector/rector image, installing required extensions inside and then running this image instead of official one.

I think example will be worth more than 1000 words:

Dockerfile:
```Dockerfile
FROM rector/rector:latest

RUN apt update && apt install -y \
    gcc \
    git \
    unzip \
    gettext \
    libicu-dev \
    libmagickwand-dev \
    libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev \
    libxml2-dev \
    libxslt-dev \
    libgearman-dev \
    zlib1g-dev \
    libc-client-dev libkrb5-dev \
    libzip-dev \
    libmemcached-dev \
    --no-install-recommends

RUN pecl install imagick && docker-php-ext-enable imagick
RUN pecl install igbinary && docker-php-ext-enable igbinary
RUN pecl install memcached && docker-php-ext-enable memcached
RUN docker-php-ext-install gettext
RUN docker-php-ext-install gd
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install soap
RUN docker-php-ext-install sockets
RUN docker-php-ext-install bz2
RUN docker-php-ext-install calendar
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install xsl
RUN docker-php-ext-install zip
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && \
    docker-php-ext-install -j$(nproc) imap
RUN docker-php-ext-install pcntl
RUN docker-php-ext-install intl
RUN pecl install apcu \
    && pecl install apcu_bc-1.0.3 \
    && docker-php-ext-enable apcu --ini-name 10-docker-php-ext-apcu.ini \
    && docker-php-ext-enable apc --ini-name 20-docker-php-ext-apc.ini

RUN git clone https://github.com/wcgallego/pecl-gearman.git \
      && cd pecl-gearman \
      && phpize \
      && ./configure \
      && make \
      && make install \
      && docker-php-ext-enable gearman \
      && cd - \
      && rm -rf pecl-gearman

RUN docker-php-ext-install xmlrpc
```

Build the image (we were using Gitlab CI to build this image for us automatically, but for now, it is enough to build it locally), name and tag it, for example: `docker build -t my-rector-with-extensions .`

Now you can use it instead of official docker image: `docker run -v $(pwd):/project my-rector-with-extensions process /project/src --level symfony28 --autoload-file /project/vendor/autoload.php --dry-run`

I will try to add the most common extensions into official Dockerfile, but i am not sure whether i am able to get there all of them (Redis or Memcached etc.) though feel free to send PR, i would accept it as more people might run into same issue.
