### ISSUE TITLE
Dry-run by default, --fix to fix.

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1626]
I started using ECS and Rector recently on my company's main project and love it so far. However, as I'm now trying to setup CI and best practices within the company, I'm noticing an inconsistency between ECS and Rector : ECS runs dry by default and needs a `--fix` flag, while Rector fixes by default and needs a `--dry-run` flag not to.

I'm using the following composer scripts so that the company's developers do not need to know all the options of these tools and make mistakes running them (like forgetting the tests/ folder or whatever) :

```
{
    "scripts": {
        "ecs": "vendor/bin/ecs --ansi check src/ tests/",
        "rector": "vendor/bin/rector --ansi process --dry-run src/ tests/"
    }
}
```

And this works very nicely with ECS, because you can run `composer ecs`, and if it shows errors, you can then do `composer ecs -- --fix` to fix them. With rector, I should have two scripts entries, one `rector-dry` and one `rector-fix`, which is not as nice.

And I love the fact that ECS shows the user this message with proper instructions : 

```
[WARNING] 1 file is fixable! Just add "--fix" to console command and rerun to apply.
``` 

What do you think ? Could it be applied to Rector as well ?

**Comment by TomasVotruba** [comment]
Thanks for your feedback. I thought of that and Rector is a bit different than other "checking tool".

Main purporse of Rector is refactor everything that can be automated for the user. It might have some obstacles from the start - that's why coding standard tools check by default - but it the end there should be no --dry-run needed. 

That's why I'm sticking wich refactor by default.
