### ISSUE TITLE
[BUG] "minimum-stability": "dev" breaks class-loading

### ISSUE THREAD

**Issue by tomasnorre** [rectorphp/rector#2335]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | ^0.6.0@dev         |
| PHP version    | 7,2,24                               |
| Full Command   | vendor/bin/rector  | 

## Current Behaviour 
```
$ vendor/bin/rector --version
[ERROR] Class 'Symplify\PackageBuilder\FileSystem\SmartFileInfo' not found
```

composer.json 
```
{
    "name": "test/test-rector",
    "minimum-stability": "dev",
    "require": {},
    "require-dev": {
        "rector/rector": "^0.6.0@dev"
    }
}
```

This happens when having `"minimum-stability": "dev",`, then the class SmarFileInfo isn't found.

As I see this, this happens as the https://packagist.org/packages/symplify/package-builder already has a new file structure which seems to be a breaking change.

Without `"minimum-stability": "dev"` it works like expected. But unfortunately not all projects are disallows dev versions.

**Comment by TomasVotruba** [comment]
That's because next release version of Symplify is going to be major on and now has BC breaks.
It's not related to Rector, this would happen with any such dependecy.

You should lock particular package in your composer.json, here symplify/package-builder to 6.1, when you want to use dev packages.

Btw, what do you need the dev option for?
Using Rector dev-master has same effect, without these troubles.

**Comment by tomasnorre** [comment]
We sometimes need the `dev` option as we include branches.

PS: Thanks for a really fast response. Will lock the `symplify/package-builder` to the 6.1 version, that helps me for now.
