### ISSUE TITLE
Remove stubs from rector.phar

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2602]
Would it be possible to remove the stubs/ folder from rector.phar to prevent PHPStorm multiple definition for classes (without having to exclude the whole phar from the project, which is useful to investigate Rectors) ?

**Comment by TomasVotruba** [comment]
No need to duplicate issue. Send PR right away

**Comment by gnutix** [comment]
Sorry, I thought you wanted the issue here. I can't provide a fix right now.

**Comment by TomasVotruba** [comment]
I meant that for future issues. 
And PR is always better than issue :)

**Comment by gnutix** [comment]
Maybe, but having an open issue assigned to me helps me know what I can do *when* I get time to contribute.

**Comment by TomasVotruba** [comment]
Without clear dead-line it often rottens. Please don't open it again and just send PR.
Thank you

**Comment by gnutix** [comment]
Then I'll forget all about it and won't do it... That's what issues are for : listing open issues. Then when someone can contribute he'll fix it. I seriously don't understand why this would be any different.

**Comment by TomasVotruba** [comment]
I think Github issues are not storage for peoples ideas. It should be important to the project, relevant, do-able and the author takes partial responsbility for the task.

I come to many dead open-source projects, buried under dozens or hundreds of similar issues. It's not easy to close them, because the closing person has to withstand the issue creator frustration. So it's left out open and the project slowly dies under pressues of 100 issuse with unclear priority.

> The repo would have hundred or thousands of issues (like some OSS repos do), I would think about it. But here? thinking

That's because I invest lot of time to keep it small and focused. This repo had around ~70 issues before Christmass, many of them in similar rotten state. It took lot of work to get under 30 most relevant ones, like bugs, unclear solutions and waiting for PR with test case.

Personally I use paper docs for it, that's place for ideas.

**Comment by gnutix** [comment]
:heavy_check_mark: Important to the project
See #1899 

:heavy_check_mark: Relevant
The problem happens again now that the PHAR is available to all.

:heavy_check_mark: Do-able
It's probably an easy pick.

:heavy_check_mark: The author takes partial responsibility for the task.
Does it looks like (https://github.com/rectorphp/rector/issues?utf8=%E2%9C%93&q=author%3Agnutix+) tons of rotten issues to you ? I think I'm quite active on this repository, be it by keeping issues alive (reporting details, etc) or by providing fixes (test cases, or even solutions).

So yes, basically, it hurts having relevant issues closed just because I can't do it "in the next 5 minutes".

**Comment by TomasVotruba** [comment]
> It's probably an easy pick.

Exactly, it could have been already resolved https://github.com/rectorphp/rector/blob/4cbaf5f3effc436c53c1d17448e5fbd7eb8e5096/compiler/build/box.json#L13

**Comment by gnutix** [comment]
The time I don't have is to **dive**. You already now how the phar is compiled, what file to look in, and probably even where's the line to change. I don't. So what you know takes a minute takes 15 for another dev (not counting context switching while the dev is at work on another project altogether).

**Comment by TomasVotruba** [comment]
You don't need to dive, you can ask. That's what I do in new repositories I don't maintain. That's how I was able to learn php-parser, just Q&A with nikic basically :)

The solution should be in previous comment.
