### ISSUE TITLE
Convert getters and setters to public properties

### ISSUE THREAD

**Issue by christian-kolb** [rectorphp/rector#3095]
# Feature Request

When working with value objects, there is a lot of boilerplate code with private properties, getters and setters. With tools like Psalm we can make the whole class readonly and then there is no need for getters and setters, as we can just use public properties. Especially because with PHP 7.4 those are typesafe. 
It would be great to have a Ractor which removes all getters and setters on PHP classes and refactors the usages of those to directly access the properties instead. Those properties would need to be updated from `private` to `public` at the same time. I'm not even sure if this is possible, but it would make refactoring of those extremely easy.

To recognize which classes have to be refactored you could check the following things:

- private property
- public `get*` and public `set*` with the "same" name
- setters only contain the assignment to the property and nothing else
- getters only contain the return of the property and nothing else
 
## Diff 

In class
```diff
- private User $user;
- 
- public getUser(): User
- {
-   return $this->user;
- }
- 
- public setUser(User $user): void
- {
-   $this->user = $user;
- }
+ public User $user;
```

Usage
```diff
- $specialUser = $object->getUser();
- 
- $otherObject->setUser($specialUser);
+ $specialUser = $object->user;
+
+ $otherObject->user = $specialUser;
```

**Comment by TomasVotruba** [comment]
Hi, this might easily lead to public property override without explicit method call. I saw similar falsy behavior often in legacy code.

Saying that, I won't add it personaly, but I can guide you to create it. E.g. under `PublicTypedProperty` package.

Here is good starting Sourse: https://github.com/rectorphp/rector/blob/master/docs/RectorRecipe.md

**Comment by christian-kolb** [comment]
@TomasVotruba Thanks for the fast reply. Is it only an issue because it might be to "global"?
Wouldn't it be possible to only apply it to a subset of the code base? I understand that there are Rectors which have to be configured. Wouldn't it be possible to build it in such a way? Then this wouldn't be an issue, would it?

**Comment by TomasVotruba** [comment]
The issue is it breaks to private scope that people expect from properties. No `set*/change*` method = no change. The property is read only.

If you remove that, you'll have to check every property if it is/isn't `public`.
That's what most legacy systems are build on now. `public` by default. If there is a bug, it can be on 50 other places, because of no strict contract.

**Comment by christian-kolb** [comment]
Ok, I will see what I can come up with and see if I can provide a pull request. I startet with this issue because it looked rector could help here, but I haven't used it myself for anything else yet. Now I found a few usecases where I could also use it. I will dive into it and try to build my own Rector for it. If it works, I will share it here as a PR.

**Comment by TomasVotruba** [comment]
Sure. When you're ready

**Comment by rvanlaak** [comment]
Now we have `readonly` since PHP 8.1, this might be something to reconsider? Maybe in combination with modifying the actual getter calls to point to the readonly properties?

Thereafter it might be worth combining with https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#classpropertyassigntoconstructorpromotionrector

Or did I possibly miss something in the huge and awesome list of rectors we currently have available already?
