### ISSUE TITLE
Running dump-rectors (on Drupal Rector project) creates broken links for classes in documentation

### ISSUE THREAD

**Issue by shaal** [rectorphp/rector#3448]
# Bug Report

Based on these instructions: https://github.com/rectorphp/rector/pull/3265

I ran: `vendor/bin/rector dump-rectors drupal-rector/src/ > drupal-rector/docs/drupal_rector_rules.md`

And created this PR https://github.com/palantirnet/drupal-rector/pull/102

The result:
https://github.com/palantirnet/drupal-rector/blob/master/docs/drupal_rector_rules.md

But if you try clicking on any of the classes links you'll get 404 page.
Example for a broken link:
https://github.com/palantirnet/drupal-rector/blob/master/drupal-rector/src/Rector/Deprecation/BrowserTestBaseGetMockRector.php

**Comment by TomasVotruba** [comment]
What exactly needs to be changed?

**Comment by samsonasik** [comment]
@TomasVotruba could you give me information about the classes that related to it ?

**Comment by TomasVotruba** [comment]
Sure. 

It's command in CLI: `Rector\DocumentationGenerator\Command\DumpRectorsCommand`

There is called markdown formatter.
In it, there is a method that dump the single Rector documentation: https://github.com/rectorphp/rector/blob/8311a555737dadb2abb462328141eb6e2629d661/packages/documentation-generator/src/OutputFormatter/MarkdownDumpRectorsOutputFormatter.php#L94

This method is probably broken for 3rd party code: https://github.com/rectorphp/rector/blob/8311a555737dadb2abb462328141eb6e2629d661/packages/documentation-generator/src/OutputFormatter/RectorPrinter.php#L74

## Expected Behavior?

It suppose to resolve file path in the dumped file, so when you click on the rule in [the generated markdown](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md), it will open the file on Github:

![here](https://user-images.githubusercontent.com/924196/91994836-5b5c9600-ed37-11ea-8773-c6f09aca2448.gif)


<br>

Let me know if you need more indicies.

This just needs hotfix, tests for path resolved are welcomed, but not neccessary

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector/pull/4115 for it.
