### ISSUE TITLE
Doctrine column annotation replacement of  colon in json 

### ISSUE THREAD

**Issue by EZarkov** [rectorphp/rector#3568]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.36               |
| Installed as   | composer dependency          |

Rector  replace `:` with '=' in json value of `options` for column annotation in 
Doctrine entity
`-     * @ORM\Column(type="boolean", name="bar", options={"default":0})` 

`+     * @ORM\Column(type="boolean", name="bar", options={"default"=0})`
Based on the example in
https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/annotations-reference.html#column it should be in json format

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1fa43acb-a977-4770-8b0f-cfc1fc1790e9
## Expected Behaviour

Rector should skip it.

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/issues/3424#issuecomment-644134589

**Comment by hkdobrev** [comment]
@TomasVotruba Thank you for the reply!

Would you consider a couple of things:

1. Rector is doing unexpected changes to the codebase without intent from the user. There is no rector rule to configure whether to change annotations or not, but it does change them anyway.
1. This is about Doctrine annotations specifically which may have different styles than Symfony. PHP CS fixer for example has Doctrine annotations rules which are different even though it uses the Symfony style for the Symfony annotations.

**Comment by TomasVotruba** [comment]
Hi,

I'm aware both cases :+1: 

It's technological limitation, there is no format preserving php doc parser in the PHP open-source tools, and Rector is trying to mimic that to the maximum possible extend. Also, because there is no standard for phpdocs and ever user and every packages handles it their own opionated way. 

As PHP 8.0 attributes with united syntax are comming, I prefer not investing time to mimic `:/=` preservation that has 0 influence on code, and rather developer core features of Rector that helps to work with bad legacy code better.

<br>

Still, I'm opened to PR that allows the configuratoin of `=/:` pet annotation type or change the defaults. See this class:

https://github.com/rectorphp/rector/blob/9d4f9b1facf36559cb4da84e19115281bb0baeb3/packages/better-php-doc-parser/src/ValueObjectFactory/TagValueNodeConfigurationFactory.php#L100-L114

**Comment by TomasVotruba** [comment]
I've just found out there is CS rule that solves this :partying_face: 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2220
