### ISSUE TITLE
Incorrect unused assignment dedection

### ISSUE THREAD

**Issue by GrahamCampbell** [rectorphp/rector#3726]
# Bug Report

<img width="643" alt="image" src="https://user-images.githubusercontent.com/2829600/87694338-f8627000-c785-11ea-9e38-4d1f369a4f6f.png">

Applied rules:

 * `Rector\DeadCode\Rector\Assign\RemoveUnusedAssignVariableRector`

**Comment by TomasVotruba** [comment]
We need reproducible demo: https://getrector.org/demo

**Comment by GrahamCampbell** [comment]
Here you go: https://getrector.org/demo/7ef107d7-452b-46d4-bec7-2189f758e3fc.

**Comment by TomasVotruba** [comment]
Thanks!

Btw, why is input mix of tabs and spaces? It makes diff hard to read

**Comment by dobryy** [comment]
@TomasVotruba, the issue occurs because there are multiple assignments for the same variable name. At the moment, the rule removes assignments and leaves just the last one. Here is the [test fixture](https://github.com/rectorphp/rector/blob/master/rules/dead-code/tests/Rector/Assign/RemoveUnusedAssignVariableRector/Fixture/assign_multi_same_line.php.inc) that describes the logic and explains the current issue.

The solution might be: Add additional check that the variable is not used in the statement (in FunctionLike params, `use` of closure and a regular statement like `$a = $a + 1;`). Is there any rule that has something similar?

**Comment by TomasVotruba** [comment]
> the issue occurs because there are multiple assignments for the same variable name

I see. Here is just used in the expression right before assigned. While in the linked fixture its only on the left side.

This should be skipped too:

```php
$values = [1, 2];
$values = $this->whatever($values);
```

> Is there any rule that has something similar?

This is rule of its own kind. I don't think so.
