### ISSUE TITLE
[Question] Alternative to the 'rector sets' command

### ISSUE THREAD

**Issue by TavoNiievez** [rectorphp/rector#3919]
## Question
How do i get the currently available sets in Rector v0.7.62?
previously i used the command `vendor/bin/rector sets` but, apparently it was removed.
i only see `Command "sets" is not defined. ` which is not very descriptive.

### Context
I'm asking this because my Travis CI build now breaks when trying to run:

```
    vendor/bin/rector process src --config rector-ci.yaml --no-progress-bar
    [ERROR] Set "doctrine" was not found
```

Build that I programmed based on the article [How to Delegate Code Reviews to CI](https://tomasvotruba.com/blog/2019/11/18/how-to-delegate-code-reviews-to-ci/), and I've noticed that the command `rector sets` is no longer available.

**Comment by TomasVotruba** [comment]
Hi, 

what is your use case? Maybe there is better solution.

<br>

Command was removed, because we're going to grow numbers of sets. Also we're moving to PHP configuration based on constant autocomplete: 

* https://twitter.com/rectorphp/status/1288874586084433925
* https://twitter.com/rectorphp/status/1289288283655036930

In CLI set names change change, which cause very unpleasant BC break, e.g.

```bash
-vendor/bin/rector --set dead-code
+vendor/bin/rector --set dead_code
```

With PHP, the class constant bears the value:

```php
SetList::DEAD_CODE // name can change withou break
```

Do you need to get list filtering? PHPStorm handles in fuzzy search:


![demo](https://user-images.githubusercontent.com/924196/89502914-0d02b880-d7c6-11ea-8dba-5f46aea0eb01.gif)

**Comment by TomasVotruba** [comment]
I'll update the post, thanks for the link

**Comment by TavoNiievez** [comment]
I understand, so basically the command is no longer needed thanks to autocompletion of the IDE based on class constants. I really like this new way much more, thanks for clarifying!

**Comment by TomasVotruba** [comment]
This should prevent more confusion: https://github.com/TomasVotruba/tomasvotruba.com/pull/1036
