### ISSUE TITLE
[docs] upgrade to symfony 3.3 without somes rules

### ISSUE THREAD

**Issue by numerogeek** [rectorphp/rector#3980]
Hello, 

I try to upgrade to SF 3.3, and when I run rector with tu rules symfony33, it runs somes rules I don't need or don't want : by example : the fluent class thing that remove the return $this in setters. 

How can I upgrade the minimum thing needed to upgrade ? 

Thank you :)

**Comment by TomasVotruba** [comment]
Hi, 

what ruleset is causing this?
What exact rule is reported?

**Comment by numerogeek** [comment]
Sounds it 
Rector\MagicDisclosure\Rector\ClassMethod\ReturnThisRemoveRector
and 
Rector\MagicDisclosure\Rector\MethodCall\FluentChainMethodCallToNormalMethodCallRector

**Comment by TomasVotruba** [comment]
In what set are they located?

**Comment by numerogeek** [comment]
```
<?php

declare(strict_types=1);

use Rector\MagicDisclosure\Rector\ClassMethod\ReturnThisRemoveRector;
use Rector\MagicDisclosure\Rector\MethodCall\FluentChainMethodCallToNormalMethodCallRector;
use Rector\MagicDisclosure\Rector\MethodCall\InArgFluentChainMethodCallToStandaloneMethodCallRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Rector\Set\ValueObject\SetList;
use Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector;
use Rector\Core\Configuration\Option;
return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    $parameters->set('auto_import_names', false);

    $parameters->set('import_short_classes', false);

    $parameters->set('import_doc_blocks', false);

    $parameters->set('sets', [
        SetList::PHP_72,
        SetList::SYMFONY_28,
        SetList::SYMFONY_30,
        SetList::SYMFONY_31,
        SetList::SYMFONY_32,
        SetList::SYMFONY_33,
        SetList::SYMFONY_34,
    ]);

    $parameters->set(Option::EXCLUDE_RECTORS, [
        FluentChainMethodCallToNormalMethodCallRector::class,
        ReturnThisRemoveRector::class,
        InArgFluentChainMethodCallToStandaloneMethodCallRector::class
    ]);

    $parameters->set('symfony_container_xml_path', __DIR__.'/var/cache/dev/appDevDebugProjectContainer.xml');

    $parameters->set('exclude_paths', ['app/DoctrineMigrations/*', 'app/cache/*', 'src/AmazonBundle/*', 'src/AllegroBundle/Model/ReturnPolicyAvailability.php']);

    $parameters->set('autoload_paths', [__DIR__.'/vendor/autoload.php', __DIR__.'/app/AppCache.php', __DIR__.'/app/AppKernel.php']);


};
```

**Comment by razvantomareea** [comment]
Having the same issue with https://github.com/rectorphp/rector-prefixed 
//    [applying] Rector\MagicDisclosure\Rector\Return_\DefluentReturnMethodCallRector
//    [applying] Rector\MagicDisclosure\Rector\MethodCall\FluentChainMethodCallToNormalMethodCallRector
//    [applying] Rector\MagicDisclosure\Rector\MethodCall\MethodCallOnSetterMethodCallToStandaloneAssignRector
//    [applying] Rector\MagicDisclosure\Rector\MethodCall\InArgFluentChainMethodCallToStandaloneMethodCallRector
I think these rules are applied due to the php version that you are running

@numerogeek  does your script  applys the symfony rules?
I have a simple config
 
return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::SETS, [SetList::SYMFONY_30]);

    $parameters->set(Option::EXCLUDE_RECTORS, [
        ReturnThisRemoveRector::class,
    ]);
};`

When running vendor/rector/rector-prefixed/rector process src --config=rector.php  -vvv --dry-run     --debug  
I don't see  the of the https://github.com/rectorphp/rector/blob/master/config/set/symfony30.php rules being applyied 
`

**Comment by TomasVotruba** [comment]
Closing as answered and fixed in linked PRs
