### ISSUE TITLE
doc generation should skip rector-recipe.php

### ISSUE THREAD

**Issue by dobryy** [rectorphp/rector#4208]
In `rector-recipe.php` I used `SetList::DOWNGRADE`. 
This constant was removed but it is still there in my rector-recipe.php, this causes an error in the console output:

> Script bin/rector dump-rectors > docs/rector_rules_overview.md handling the docs event returned with error code 1

and in the `rector_rules_overview.md:
> [ERROR] Undefined class constant 'DOWNGRADE'

**Comment by TomasVotruba** [comment]
This is due to preventing the other bug of `rector-recipe.php` not autoloaded. 

The feature was added here: https://github.com/rectorphp/rector/commit/de4748f935a3d7f14de6348d0de97507fc12cc14#diff-a3a07e80db865b763fec95cb0290533c
It might be confusing to load some configs just sometimes.

There should never be dead code in configs, so this error makes sense. 
The solution is to remove dead code.

**Comment by dobryy** [comment]
I see... I didn't consider it as some config. I considered it as some tool that shouldn't break anything if incorrect.
Maybe it is not a problem that it is autoloaded.The problem is that error messages are not straightforward enough to figure out what is wrong and since `rector-recipe.php` is in `.gitignore` even cleaning all changes in the master branch doesn't solve the problem :-/

**Comment by TomasVotruba** [comment]
I see, that sounds frustrating.
How could we narrow this error better right to the file?

**Comment by TomasVotruba** [comment]
I had an idea... what `rector-recipe.php` would be only included on `generate` command?

It would require to update this line to check for passed command name:
https://github.com/rectorphp/rector/blob/88d57114364c1f86b7a46cbb3e0dcf06838e8389/src/Bootstrap/RectorConfigsResolver.php#L85

What do you think?

**Comment by dobryy** [comment]
Sounds like a good solution.
