### ISSUE TITLE
Deactivate fix of code style?

### ISSUE THREAD

**Issue by malteschlueter** [rectorphp/rector#4287]
# Is it possible to deactivate that rector fixes code style?
i.e.
* it refactors multiline methods to single line
* it removes empty comments.
* Removes class aliases and inserts the FCQN

For code style i prefer the PHP CS Fixer.

**Comment by TomasVotruba** [comment]
Hi, this is limitation due to php-parser, that we can't handle - see https://github.com/rectorphp/rector#how-to-apply-coding-standards for more.

<br>

In some rare cases can help to  de-activate specific rules that are doing the changes, or fiddle with configuration, [see README](https://github.com/rectorphp/rector#configuration): 

```php
    $parameters->set(Option::AUTO_IMPORT_NAMES, true);
    // skip root namespace classes, like \DateTime or \Exception [default: true]
    $parameters->set(Option::IMPORT_SHORT_CLASSES, false);
    // skip classes used in PHP DocBlocks, like in /** @var \Some\Class */ [default: true]
    $parameters->set(Option::IMPORT_DOC_BLOCKS, false);
```
