### ISSUE TITLE
Running Downgrade on the lower PHP version

### ISSUE THREAD

**Issue by szepeviktor** [rectorphp/rector#4388]
# Question

Hello! I'd like to fork a PHP 7.4 package and publish it as PHP 7.1+
My computer has PHP 7.3

Will I be able to run Rector with `SetList::DOWNGRADE_PHP74`?

**Comment by szepeviktor** [comment]
![kép](https://user-images.githubusercontent.com/952007/95655933-116f8880-0b0b-11eb-9eec-f6828f86e1a4.png)

**Comment by szepeviktor** [comment]
![kép](https://user-images.githubusercontent.com/952007/95656041-d3269900-0b0b-11eb-8c67-e868460be5d2.png)

**Comment by TomasVotruba** [comment]
I think to process PHP 7.4 code, you need to run PHP 7.4.

On the other hand, I plan to do this here and on @symplify via Github Actions (= automate it), where you can pick any PHP version).

What is your experience @leoloso ?

**Comment by szepeviktor** [comment]
Leo, the one with a pen that never runs out :)

**Comment by leoloso** [comment]
Hi @szepeviktor 👋

Yeah, for downgrading, you need PHP 7.4 to transform PHP 7.4 code, otherwise it throws an error when parsing the file.

It doesn't happen the other way around: to modernize code from PHP 7.3 to 7.4, you can run 7.3, since 7.4 code is an output (using the inner elements from PHP-Parser), not an input (which must be parsed by the PHP engine)

If you can't upgrade to PHP 7.4, maybe you can [run Rector in Docker](https://github.com/rectorphp/rector#run-rector-in-docker)?

**Comment by szepeviktor** [comment]
> If you can't upgrade to PHP 7.4, maybe you can [run Rector in Docker](https://github.com/rectorphp/rector#run-rector-in-docker)?

Thank you! Vercel Now will help me :)
