### ISSUE TITLE
Docker Image runs as root

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#4568]
# Bug Report

Rector runs as root. The permissions of all files are broken.

Overriding the user does not help:

```
❯ docker run --rm -v (pwd):/project -u1000 rector/rector:latest process src

 [ERROR] Unable to write in the "cache" directory (/tmp/_rector).     
```

**Comment by TomasVotruba** [comment]
cc @JanMikes

**Comment by JanMikes** [comment]
Hi, thank you for bug report.

I do not fully understand what is the problem and i want to understand what is your usecase.

Why do you need to run it with non-root?

**Comment by shyim** [comment]
Why does this app need permission as root?
Any file written by rector is owned by root I can't modify it as my user.

**Comment by JanMikes** [comment]
> Why does this app need permission as root?

Actually it does not need it, but it is really convenient to not hack around it. 

This image is not intended to be used in production environments and for dev purposes, i suppose it is completely ok. i always had a lot of troubles tweaking to perfection non-root user for images that run in different OSs (mac, windows, linux) and in my experience, it is best to keep root user.

> Any file written by rector is owned by root I can't modify it as my user.

This is weird and i want to know more! running rector in docker should not anyhow modify your host filesystem, only files mounted via volume and these should keep their original permissions.

**Comment by shyim** [comment]
I run it like here and all my permissions got broke.
https://github.com/rectorphp/rector/blob/master/docs/how_to_run_rector_in_docker.md

**Comment by JanMikes** [comment]
What OS do you have?

**Comment by shyim** [comment]
Linux

**Comment by JanMikes** [comment]
Thx, please feel free to share any relevant information, i will be trying to reproduce.

So if i understand what exactly your issue is:
1. `ls -l` before running rector, files are owned by your user
2. you run this command: `docker run --rm -v $(pwd):/project rector/rector:latest process src --set symfony40 --dry-run`
3. `ls -l` and files are owned by root

Do you have any fix proposals?

**Comment by shyim** [comment]
```
/tmp/bla via 🐘 v7.4.11
❯ ls -la
total 32
drwxr-xr-x  2 shyim shyim  4096 Nov 18 14:47 ./
drwxrwxrwt 27 root  root  20480 Nov 18 14:45 ../
-rw-r--r--  1 shyim shyim    28 Nov 18 14:47 index.php
-rw-r--r--  1 shyim shyim   719 Nov 18 14:46 rector.php

/tmp/bla via 🐘 v7.4.11
❯ docker run --rm -v (pwd):/project rector/rector:latest process index.php
Rector dev-master@b4fd520
Config file: rector.php

 0/4 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) index.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -1,5 +1,3 @@
 <?php

 return 0;
-
-return 1;
    ----------- end diff -----------


Applied rules:

 * Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector


 [OK] Rector is done! 1 file has been changed.


/tmp/bla via 🐘 v7.4.11
❯ ls -la
total 32
drwxr-xr-x  2 shyim shyim  4096 Nov 18 14:47 ./
drwxrwxrwt 27 root  root  20480 Nov 18 14:45 ../
-rw-r--r--  1 root  root     17 Nov 18 14:47 index.php
-rw-r--r--  1 shyim shyim   719 Nov 18 14:46 rector.php
```

**Comment by JanMikes** [comment]
Thank you @shyim this is perfect and helps a lot! 👍

**Comment by rieschl** [comment]
I also ran into this problem. I want run the docker container as "me" and not root because rector changes the file permission of processed files to root (probably because the file is created from scratch and then copied back to the project) and after processing I can't write to the modified files anymore.

So, I just tried to run the command with `--user $(id -u):$(id -g)`:
`docker run --rm --user $(id -u):$(id -g) -v $(pwd):/project rector/rector:latest process src --config rector.php --dry-run`

But that throws an error `[ERROR] Unable to write in the "cache" directory (/tmp/_rector)`.

The first "solution" is to just ignoring the `/tmp` folder in the container with an additional parameter `-v /tmp:/tmp`:

`docker run --rm --user $(id -u):$(id -g) -v /tmp:/tmp -v $(pwd):/project rector/rector:latest process src --config rector.php --dry-run`.

That's working, but kind of ugly. So I tried to get to the root of the problem. Something in the container's `/tmp` file seems to cause issues:
```
$ docker run -it --rm --entrypoint "/bin/ls" rector/rector:latest -alh /tmp
total 36K
drwxrwxrwt 1 root root 4.0K Nov  4 14:56 .
drwxr-xr-x 1 root root 4.0K Nov 21 21:55 ..
drwxr-xr-x 3 root root 4.0K Nov  4 14:56 _rector
drwxr-xr-x 3 root root 4.0K Nov  4 14:56 _rector_cached_files
drwxr-xr-x 2 root root 4.0K Nov  4 14:56 _rector_log
drwxr-xr-x 2 root root 4.0K Nov  4 14:56 _rector_stubs
drwxr-xr-x 3 root root 4.0K Nov  4 14:56 cache
drwxr-xr-x 1 root root 4.0K Nov  4 14:56 opcache
drwxr-xr-x 5 root root 4.0K Oct 30 11:59 pear
```

The folder is not empty and the directory `/tmp/_rector` already exists and is owned by root.
That's because in the [Dockerfile rector is already being executed](https://github.com/rectorphp/rector/blob/master/Dockerfile#L38).
I haven't tried it yet, but probably removing the contents of the `/tmp` folder or `chmod`ing everything to `777` in the `Dockerfile` would solve that issue.

Thanks!

**Comment by JanMikes** [comment]
Hi, there is intentionally running rector in dockerfile itself, to warmup cache and make sure rector can be run itself.

Please try to run `rector/rector:fix-4568` if that helps you, if you could confirm, it would be awesome.

Check https://github.com/rectorphp/rector/commit/b3c83bd341302646d93479cfcf6a3dc81ee2b828 for more info.

**Comment by shyim** [comment]
```
/tmp/bla via 🐘 v7.4.11 took 18s
❯ docker run --rm -u1000:1000 -v (pwd):/project rector/rector:fix-4568 process index.php

 [ERROR] Unable to create file
         '/tmp/_rector_stubs/7ba983888879c5dfc11be38815c040e2.php.lock'.
         fopen(/tmp/_rector_stubs/7ba983888879c5dfc11be38815c040e2.php.lock):
         failed to open stream: Permission denied
```

**Comment by JanMikes** [comment]
im sorry🤦 yeah forget `-R` for `chmod` 

Can you please `docker pull rector/rector:fix-4568` and try again?

**Comment by shyim** [comment]
```
Notice: Nette\Utils\Strings::toAscii(): it is recommended to enable PHP extensions 'intl'. in /rector/vendor/nette/utils/src/Utils/Strings.php on line 152
Rector dev-master@578751e
Config file: rector.php

 0/4 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) index.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -1,5 +1,3 @@
 <?php

 return 0;
-
-return 1;
    ----------- end diff -----------


Applied rules:

 * Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector


 [OK] Rector is done! 1 file has been changed.
```

Maybe install intl extension too :D
