### ISSUE TITLE
Dump Node Tree

### ISSUE THREAD

**Issue by JoyceBabu** [rectorphp/rector#5132]
# Question

If I remember correctly, there used to be a command that allowed dumping the Node Tree for a file, for analysing the current structure when writing new Rectors.

But I couldn't find any such command when running `./vendor/bin/rector list`. Was it removed?

**Comment by TomasVotruba** [comment]
Hi,

yea, there was somethine like a `screen-file` command, that dumped nodes with *some* metadata.
It was not very used and turned out to be very problematic to show all relevant metadata. Different people needed different metadata :)

The simple `dump()` function provided similar features.

Also, you can check this package that helps with printing:
https://github.com/matthiasnoback/php-parser-instantiation-printer

What exactly is your use case?

**Comment by JoyceBabu** [comment]
I was trying to write a rector and found it tedious to check the method declaration / documentation everytime I encountered a new Node type.

`dump()` and `php-parser-instantiation-printer` will help immensely. Thank you.

**Comment by TomasVotruba** [comment]
I see. 
We've added `print_node()` function for such cases too. It would be great to improve it based on yours feedback
