### ISSUE TITLE
[PHPExcel] migration to [PhpSpreadsheet]

### ISSUE THREAD

**Issue by kjeanson** [rectorphp/rector#6171]
Hi,

I try to migrate PHPExcel to PhpSpreadsheet.

Everything is ok (composer require / rector.php config file)

I have a /tests/PHPExcelTest.php file for PHPUnit wich is containing a PHPExcel sample :
`$objPHPExcel = new PHPExcel();
...`

When i run **vendor/bin/rector process tests/** i have a progressbar 52/52 and a green message **[OK] Rector is done!** but nothing append. My "new PHPExcel" is not replace by PhpSpreadsheet.

Do you have any idea ?

Thanks.

**Comment by sabbelasichon** [comment]
I think this is a bug related to the problem that the class PHPExcel does not exists in your project and is not replaced.
In order to check this try to create a stub class PHPExcel and load the stubs via composer´s autoloading classmap mechanism.
https://github.com/rectorphp/rector/blob/main/composer.json#L103

**Comment by sabbelasichon** [comment]
If you can verify that after adding the class it worked i am gonna create a failing PR for that.

**Comment by sabbelasichon** [comment]
@TomasVotruba That´s definitely related to this issue here: https://github.com/sabbelasichon/typo3-rector/issues/2161.

If you are saying, that should be possible without autoloading this would be great. If not or maybe as in between step, we could you use this neat but very smart library here: https://github.com/TYPO3/class-alias-loader. 

So if we provide all the old classes we are coming from in a ClassAliasMap the problem is gone. I am using exactly this approach in my projects. But this still requires autoloading. What do you think?

**Comment by TomasVotruba** [comment]
> If you are saying, that should be possible without autoloading this would be great.

That's the goal here, as there is no type check needed. The replacement is basically `string` for `string`. Current implementation of class renamer is wrong.

**Comment by kjeanson** [comment]
@sabbelasichon thanks for your quick reply

I added a classmap on my composer.json
`"classmap": [`
`"vendor/phpoffice/phpexcel/Classes"`
`]`

now when i run `vendor/bin/rector process tests` it seems to load PHPExcel library because i have the following PHP Deprecated messages 
`Deprecated: Array and string offset access syntax with curly braces is deprecated in /vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/String.php on line 542`
but still no replacement...

I tried to add composer´s autoloading files `"vendor/phpoffice/phpexcel/Classes/PHPExcel.php"`, but same issue...

**Comment by sabbelasichon** [comment]
@TomasVotruba Do you think it could help to add stubs for this? For me in typo3-rector it works perfectly now. I thinks it is somehow related. See: https://github.com/sabbelasichon/typo3-rector/commit/c924f8cbc3400238458f5ff09dae8404664a3a00#diff-5d6f21616131ebbf56ab692f8d9f7cef73b1c7167c5a33e8fd7bc8262cb3a2c5R4

**Comment by TomasVotruba** [comment]
@sabbelasichon I haven't looked into this yet.
Failing PR with this use case would help me to look into this closer.

**Comment by sabbelasichon** [comment]
@TomasVotruba I am not able to create a failing test for that. It works perfectly as you said. 

@kjeanson Never asked before, but what version of rector are you using? In current master it works perfectly without having any related classes in place.

**Comment by TomasVotruba** [comment]
@kjeanson We'll need a reproducible repository on Github to verify.

**Comment by TomasVotruba** [comment]
Thanks! I'm looking into it

**Comment by TomasVotruba** [comment]
When running with `--debug`:

```bash
vendor/bin/rector process tests
```

It seems the problem is with `protected` method:

![image](https://user-images.githubusercontent.com/924196/116383524-34e3f180-a817-11eb-8e59-caddeb104601.png)



This file is included by composer, so it's invoked:

```json
{
    "autoload": {
		"files": [
			"services/Intranet/Autoloader.php"
	    ],		
	}
}
```

Making it `public` fixes public call and works  :+1: 

![image](https://user-images.githubusercontent.com/924196/116383775-76749c80-a817-11eb-821e-424361cfcfff.png)

**Comment by TomasVotruba** [comment]
There is one more problem if the whole fixture is included. I'm looking into it

**Comment by kjeanson** [comment]
@TomasVotruba Thanks a lot ! It finally works when i comment the `throw new PHPExcel_Writer_Exception` line 8 in files : 
`vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/PDF/DomPDF.php`
`vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/PDF/mPDF.php`
`vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/PDF/tcPDF.php`
