### ISSUE TITLE
Rector-prefixed does not show correct version

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#6178]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector dev-main@{no ref              |
| Installed as   |  prefixed Rector                           |

```
$ vendor/bin/rector --version
Rector dev-main@{no ref

$ composer show | grep rector-prefixed
rector/rector-prefixed                  0.10.6             Prefixed and PHP 7.1 downgraded version of rector/rector
```

**Comment by TomasVotruba** [comment]
It was due to conflict with PHPStan version provider, that has the same `InstalledVersion` class.

Fixed via:

- https://github.com/rectorphp/rector/commit/3901ae3d1fe8ca3625251d851836f661cd2ba01a
- https://github.com/rectorphp/rector/commit/00fcdc1f03666097084974ba6826f73a1f088a12
- https://github.com/rectorphp/rector/commit/12564db7af426b32ca27437302b0b11854b612df
- **https://github.com/rectorphp/rector/commit/26d6fff51d6dbf5030a140cd3705ef73c99bf4b1**
- https://github.com/rectorphp/rector/commit/176258ce5c50696d078855ea38d78d090d2eefcc
- https://github.com/rectorphp/rector/commit/61d9704afd7a840f67d94cf08b0c3526e246b110
- https://github.com/rectorphp/rector/commit/835ec0b618ede3412cac9247cd440011edb89dec

![image](https://user-images.githubusercontent.com/924196/116592212-09006300-a920-11eb-94b7-dea636494e02.png)
