### ISSUE TITLE
Improve commit messages

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#6423]
Today Dependabot created a PR to bump Rector to a new release 🎉  Always great to see these updates 🎉 

I often click Commits toggle to see what changed, but then I see:
<img width="1023" alt="Screenshot 2021-05-17 at 08 54 59@2x" src="https://user-images.githubusercontent.com/104180/118444652-b8458400-b6ed-11eb-86d3-53d7201bbbca.png">

Can this be fixed? Ideally, the original commit message should be visible. This used to work fine, but seems to be broken.

**Comment by TomasVotruba** [comment]
Hi, we're using the same convention as PHPStan does https://github.com/phpstan/phpstan

The hash in rector/rector links the original commit message rector/rector-src.
It groups multiple commits since last merge: https://github.com/rectorphp/rector/commit/097456e85f71e34f81ba52867cc9140104af4641

![image](https://user-images.githubusercontent.com/924196/118491193-03c45600-b71f-11eb-8eb2-467aa32bdb76.png)

Having 1 long line of 10 commits in 1 would look also mess, so we'll stick with this naming.

It would be better to display these subcommits in the dependabot PR :+1:
