### ISSUE TITLE
phpstan is out of date

### ISSUE THREAD

**Issue by garak** [rectorphp/rector#6428]
Is there a reason to pin phpstan dependency to patch version?
If this can't be changed, can you please update phpstan/phpstan to 0.12.88?

**Comment by TomasVotruba** [comment]
Hi, yes, we need to use PHPStan version that has compatible php-parser.
https://github.com/phpstan/phpstan-src/blob/18f8473fa5c8e957f5e24d25961160ac89afd506/composer.json#L24

Unfortunately this information cannot be locked by our `composer.json`, because `php-parser` is hidden and scoped inside PHPStan code. We used to have this dependency opened for PHPStan and it crashed Rector coupled of times for this reason.

Yet if Rector and PHPStan share the same `php-parser` versoin, it can be opened to it. E.g.:

```diff
-"phpstan": "0.12.85"
+"phpstan": ">=0.12.85 || <= 0.12.88"
```

Could you send PR?

**Comment by garak** [comment]
I'd be glad to propose a PR, but I'm not sure to understand the proposed solution.
How can I know if rector and phpstan share the same version of such vendor? Does it make sense to declare an "OR" constraint with overlapping boundaries?

**Comment by TomasVotruba** [comment]
> How can I know if rector and phpstan share the same version of such vendor?

We have to check `composer.json` of phpstan-src (the one I linked):
https://github.com/phpstan/phpstan-src/blob/18f8473fa5c8e957f5e24d25961160ac89afd506/composer.json#L24

And rector-src: https://github.com/rectorphp/rector-src/blob/92358f779952cca81bfd73fe3228e00135d6919b/composer.json#L21

> Does it make sense to declare an "OR" constraint with overlapping boundaries?

I don't use there constraints so I'm not sure. I would use the constraint that allows install the most PHPStan versions that shares the same php-parser version with Rector :)
