### ISSUE TITLE
heredoc printing windows problem:

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6486]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. https://github.com/rectorphp/rector-src/commit/2344fdb6e4898084622d62ba2a88e77d32d4fed2             |

## Minimal PHP Code Causing Issue

it seems there is some buggy pattern in heredoc printing on windows

see https://github.com/rectorphp/rector-src/pull/120/checks?check_run_id=2747711049

the ending semicolon seems to be printed on a separate line

![grafik](https://user-images.githubusercontent.com/120441/120837062-901ba900-c566-11eb-8cf8-9ef1abc5497d.png)

since I observed this problem in different unit test, I figured it might be some underlying common problem and I should report a issue for it.

## Expected Behaviour

the ending `;` should be on the same line as the heredoc marker

**Comment by staabm** [comment]
for completelyness.. same here:

![grafik](https://user-images.githubusercontent.com/120441/120837565-22bc4800-c567-11eb-9948-9ca77dc74362.png)

**Comment by staabm** [comment]
hmm interessting .. cannot reproduce on my personal windows laptop

**Comment by TomasVotruba** [comment]
Thanks for reporting. This could grow into huge list of Windows-related issues, and clutter the issue tracker. Mostly is related to whitespace/newlines, common case for Windows. Instead of reporting every single rule, **it is more useful to fix the found cases via PR**.

Saying that, I'm closing this issue to keep focus on general issues affecting any OS.
Thank you for understanding.
