### ISSUE TITLE
Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector

### ISSUE THREAD

**Issue by freiondrej-economia** [rectorphp/rector#6560]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.11.16      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebdf131-b755-6d14-87dc-3bd61a8604bc

```php
<?php

class Test
{
    private object $object;
    
    public function __construct(object $object)
    {
        // some comment above
        $this->object = $object;
        // some comment below
    }
}
```

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

The "// some comment above" should not be deleted. Instead, rector wants to delete it (while "//some comment below" is kept as expected).

**Comment by rajyan** [comment]
I think this is how nikic PHP-Parser handle comments.
```
public function __construct(object $object)
    {
        // belongs to $this->object = $object
        $this->object = $object;  // belongs to $this->object = $object
        // belongs to Nop
    }
```
That makes sense, because people write comments for `$this->object = $object` on these places.
As this node is removed by rector, the comment would be removed too.

In my opinion, there is no reason to leave the comment there, but maybe moving the comment to the `__construct` is reasonable?
What do you think about it? @freiondrej-economia

**Comment by TomasVotruba** [comment]
I would answer the same way as @rajyan :+1:  That's how php-parser and coding standard handle comments.

I recall slevomat cs has some rule to move "behind comments" above the node you expect - https://github.com/slevomat/coding-standard

Otherwise you'll have to implement your own custom rule to handle this situation first, either in tokens or in AST.

**Comment by freiondrej-economia** [comment]
@rajyan thank you for your input.
@TomasVotruba I see.
The reason I primarily created this issue is because it potentially (just my opinion) decreases trust into Rector - I guess new users can have some amount of skepticism towards automated refactoring and realizing it deleted something potentially of value seems quite scary (deleting a comment cannot be detected by automated tests / phpstan, as opposed to a hypothetic situation when some part of real code gets deleted).
After thinking about that, I suggest reopening this issue; while I understand the technical reasoning, I think that in this situation removing the node is unexpected from user perspective - a user (myself included) would rather expect the code to "move" instead of "being removed and recreated, but without the comment".
WDYT? :)

**Comment by TomasVotruba** [comment]
Understood :+1: In the end, this taught me to fix comments into code. When I need to comment, I'm lazy to come with propper solution on correct layer.

To other topic: using AST is scary area, like using new framework instead of plain PHP. This is part of PHP-related knowledge. PHPStan and coding standards will report you same error, e.g. if you put `@var` under the variable. There is different rule in Symplify coding standard that fixes it.

I think it's not about fear or trust, but rather about knowledge. You'll come across many WTFs while working with AST (whether in Rector or PHPStan or your custom traversers). If you want to save slow onboarding, get somebody who works with AST on the team or training.

**Comment by freiondrej-economia** [comment]
@TomasVotruba while that's mostly a good approach, I think there can be situations when a comment is the best way to go. But that's probably matter of personal preference :)

As far as knowledge is concerned, I agree that it's best to know, I already bought your book on Rector 🙂 as @rajyan suggested, in this case I'd expect the node will not be outright deleted, but perhaps moved to __construct. But of course that's just my subjective feeling.

To get more technical, I also tried a `/**/`-style comment, which is also deleted https://getrector.org/demo/1ebdfc4e-3d6c-6c32-be44-075ff46860ac. I suppose that's the same from php-parser's point of view? :) 

If that's the case and you feel this is proper behavior, I surely don't want to take any more of your time. Just made the point to discuss the possible wtf-moment for a newcomer rector user :)

**Comment by freiondrej-economia** [comment]
@TomasVotruba having thought about this more during the weekend, I thought of the following:

> In the end, this taught me to fix comments into code. When I need to comment, I'm lazy to come with propper solution on correct layer.

While I agree from the best-practice standpoint, I don't think this is valid from Rector's point of view - it should be able to work properly even when the code is suboptimal.

> I think it's not about fear or trust, but rather about knowledge.

I've come to think that this situation is not actually related to knowledge, at least not to AST knowledge. Let me explain: Even knowing AST and PhpParser perfectly, I probably wouldn't expect the comment to be outright deleted when moving the node. So the knowledge I would have to possess in this case would be to know the corresponding **Rector rule** and that it thows the comment away. But this knowledge is unreliable, because the rule can be changed over time, which is not the case (or at least much less the case) with AST and PhpParser behavior. So to sum up, I believe my original problem is that ClassPropertyAssignToConstructorPromotionRector does something which is not very predictable.

What do you think? :) does that explain my point in a better way?

**Comment by TomasVotruba** [comment]
I think we choose this way to focus rather on main features and new rule, then to spend same time on doc tokens. So any improvement is welcomed here :+1:

**Comment by freiondrej-economia** [comment]
@TomasVotruba I understand :) I'll try to prepare a PR as soon as I have some time.
