### ISSUE TITLE
Docker Hub image is not avalible

### ISSUE THREAD

**Issue by slis-herold** [rectorphp/rector#6647]
Hey guys,

we use your great software in all our CI processes, so we noticed that your official docker image is N/A at Docker Hub.

https://hub.docker.com/r/rector/rector/

Just wanted to let you guys know.

**Comment by TomasVotruba** [comment]
Hi, thanks for checking with us.

The Docker was causing headaches to most users. It was useful, but since Rector 0.11, that is needed prefixed & downgraded version it was only burden without added value. Saying that we dropped it to promote native Rector and make easier to use Rector in projects.

See:

* https://getrector.org/blog/dropping-docker-in-favor-of-composer-install-for-better-developer-experince
* https://github.com/rectorphp/rector-src/pull/614#issue-705879427

**Comment by cavo789** [comment]
It's a sad news. Was so easy (and working!) to use rector on docker. So easy, so useful, so wow!

With composer, globally, was not OK due to conflits and docker was a perfect solution adressing that issue.

So now the only one solution is to install rector locally on each repo and perhaps meet conflits with another depedencies...

It's a sad news and I trust you when you say it was buggy (but not for me).

Thanks for your work.

**Comment by TomasVotruba** [comment]
>  and perhaps meet conflits with another depedencies...

That's exactly what is resolved since 0.11. See https://getrector.org/blog/prefixed-rector-by-default
