### ISSUE TITLE
Where to find and how to use Symfony Set?

### ISSUE THREAD

**Issue by koko236** [rectorphp/rector#6669]
# Question
Hi, 
I came across Rector when upgrading a larger project a few months ago but I decided to do it by hand and now I would like to try it ona smaller one we work on with a few more waiting in line. First I want to upgrade a project from Symfony 3.4 to 4.x and I'm having a silly problem with it. 

I installed rector:0.11.52 using `composer require rector/rector --dev`. From what I understand it should have rules set for Symfony included, but I cannot find it anywhere in the vendor/rector directory. My autocomplete adds 

`use Rector\Symfony\Set\SymfonySetList;` 

directive in `rector.php` file but when I try to navigate there i get following error: 

`Error: Unable to resolve non-existing file /Users/konrad/Sites/[project-name-removed]/vendor/rector/rector-symfony/src/Set/SymfonySetList.php')`.
 
Also when I run :

`vendor/bin/rector process src --dry-run` 

There is no error but I get only some very minor changes in 4 files. 

My rector.php looks like that (following the readme here https://github.com/rectorphp/rector-symfony/blob/main/README.md): 
```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Rector\Symfony\Set\SymfonySetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    // Define what rule sets will be applied
    // $containerConfigurator->import(SetList::DEAD_CODE);
    $containerConfigurator->import(SymfonySetList::SYMFONY_40);

    

    $parameters->set(Option::SKIP, [
        __DIR__ . '/src/*/Tests/*',
    ]);

    $parameters->set(
        Option::SYMFONY_CONTAINER_XML_PATH_PARAMETER,
        __DIR__ . '/var/cache/dev/AppKernelDevDebugContainer.xml'
    );

    // get services (needed for register a single rule)
    // $services = $containerConfigurator->services();

    // register a single rule
    // $services->set(TypedPropertyRector::class);
};
```
I suspect this is some noob mistake I'm making and I'd be really grateful for any nudge in the right direction. :-)

**Comment by TomasVotruba** [comment]
Hi, thank you for clear description :+1: 

All the availble rules are in this Github repository: https://github.com/rectorphp/rector-symfony

Not sure why your IDE does not load the file (just tried one import that uses rector/rector as dependency and it opens the file directly, using PHPStorm). But you can find it in `/vendor/rector/rector/vendor/rector-symfony`. The [Rector package is scoped and uses projects as split dependencies](https://getrector.org/blog/prefixed-rector-by-default), that's why this path has extra vendor in it.

> There is no error but I get only some very minor changes in 4 files.

It's possible that:

* path in `rector.php` is incorrect, should be both `app`, `config`,`src` and `tests` probably
* the ruleset is missing an upgrade rule that your code needs

May be the case your project does not have anything to upgrade in Symfony 4.0, usually it's the same as previous versions Symfony 3.4, so be sure use that too :)

**Comment by koko236** [comment]
Thanks for the quick reaction! 
Ok, I found the rector-symfony. I'll try to mess with adding sources to files and review the rules to see which might be used. I'll post an update for future generations if I get it to work. ;-)

**Comment by TomasVotruba** [comment]
Closing as answered :+1:
