### ISSUE TITLE
Missing cases in CompleteDynamicPropertiesRector

### ISSUE THREAD

**Issue by afilina** [rectorphp/rector#6806]
# Feature Request

I went through the [test cases](https://github.com/rectorphp/rector-src/tree/main/rules-tests/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector/Fixture) and couldn't find these two.
 
## Diff 

1. Nothing seems to explicitly address dynamic properties created from outside the class itself. I suspect that there will be plenty of cases where a variable's class can't even be detected, or messed up due to multiple classes of the same name (projects with no autoloading, or mutually-exclusive autoload configs). Executable: https://3v4l.org/HFICt

```diff
class A
{
+ private $dynamic;
}

$a = new A();
$a->dynamic = 'xyz';
```

2. I don't know whether there's an easy way to track down unserialized classes, but I just wanted to throw that case in here for your consideration. Executable: https://3v4l.org/IOSUB

```
class A
{
}

$a = new A();

$serialized = serialize($a);
$unserialized = unserialize($serialized);
$unserialized->dynamic = 'xyz';
```

**Comment by TomasVotruba** [comment]
Hi, thanks for checking these cases.

1. Due to PHPStan design that we inherit here, we can only work with current context. That means PHPStan does not know about all use cases, just about current class. E.g. dead public methods cannot be reported etc. This might change in the future, but so far there is nothing we can do about it.

2.  In this case, it depends what type PHPStan can detect on this line:

```php
$unserialized->dynamic = 'xyz';
```

IMO if you get a string, it's impossible to statically detect what class it is.

**Comment by afilina** [comment]
Perhaps we can detect unserialize+dynamic, and warn the dev that they should probably add a type hint on the unserialize line. From there, we can extrapolate the rest.

**Comment by TomasVotruba** [comment]
> Perhaps we can detect unserialize+dynamic

That makes sense :+1: We could add PHPStan rule for that. If you can come upt with simple example in https://github.com/symplify/symplify issues, I can draft a rule there

**Comment by TomasVotruba** [comment]
Closing as answered and out of scope for Rector.
