### ISSUE TITLE
conflict with phpstan 0.x

### ISSUE THREAD

**Issue by dbu** [rectorphp/rector#6810]
# Question

Reading up on the installation instructions, rector/rector should be installable anywhere. However, we have a project that is on phpstan 0.12 atm and upgrading to 1.x will take a moment. I can't install the latest rector/rector because it wants phpstan 1. Looking at composer.json, phpstan is the only thing that is listed as an actual dependency (if i understand correctly, everything else is namespaced and committed to vendor)

is there a technical reason that phpstan is treated differently, or was that some oversight?

**Comment by TomasVotruba** [comment]
Hi, thanks for the question. 

Rector is using PHPStan to detect types. We also both share php-parser, which version must be in sync.
PHPStan is already prefixing its dependencies, to allow easy install anywhere. Doing the same is technically possible, but would take months of work to do propperly and might not even work. That's why we decided to use PHPStan as only non-prefixed dependency. It also makes upgrade of Rector and PHPStan together easier.

See https://github.com/rectorphp/rector/issues/6744 for more

**Comment by dbu** [comment]
thanks a lot for the explanation and the fast response! i will then continue with the phpstan upgrade first.

if more people ask this, maybe you could add a short note in https://github.com/rectorphp/rector#install that rector prefixes most dependencies to not clash with the application, but phpstan is the one exception.
