### ISSUE TITLE
Rename namespace failed on symfony based skeleton

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector#6837]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  v0.12.5           |

## Minimal PHP Code Causing Issue

Currently could not create a reproduceable on the getrector demo instead I have created a repository where the problems appears.

https://github.com/alexander-schranz/rector-namespace-rename-reproducable

> `PHP Fatal error:  Uncaught TypeError: RectorPrefix20211123\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator::__construct(): Argument #1 ($container) must be of type RectorPrefix20211123\Symfony\Component\DependencyInjection\ContainerBuilder, Symfony\Component\DependencyInjection\ContainerBuilder given, called in /private/tmp/skeleton/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php on line 155 and defined in /private/tmp/skeleton/vendor/rector/rector/vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php:37`

## Expected Behaviour

Should not fail and should in the second run fix the AUTO_IMPORT flag when the directory is renamed correctly.

**Comment by alexander-schranz** [comment]
Found out the error is maybe more a problem in combination with the Symfony PHPStan implementation.

As it seems to work correctly after calling:

```
bin/console cache:clear
```

After the first try. I'm using 2 runs of rector because the first run does not correctly AUTO_IMPORT the use statements after the namespace was renamed.

**Comment by TomasVotruba** [comment]
Hi, thanks for sharing and investigation.
This will be more likely autoloading issue.

Could you create reproducible repository with reproducible failing Github action?

**Comment by alexander-schranz** [comment]
@TomasVotruba I added the github action here:

https://github.com/alexander-schranz/rector-namespace-rename-reproducable/pull/1

**Comment by TomasVotruba** [comment]
Thanks :+1: I'm just looking into it.

The bug is cause by `tests/phpstan/console-application.php`, required in `phpstan.neon`

```yaml
includes:
    - vendor/phpstan/phpstan-symfony/extension.neon
```

Without these 2 files, the Rector runs correctly.
I'm investigating more.

**Comment by TomasVotruba** [comment]
The main room seems in mixing static reflection and dynamic include.

The Symfony PHPStan plugin violates static reflectoin by including project DI factory and creating a console application. Due to this, the project is actually autoloaded twice. That should not happen, see https://phpstan.org/blog/zero-config-analysis-with-static-reflection

The responsible line is https://github.com/phpstan/phpstan-symfony/blob/edb55af46fe1aaa62fafae51c36ccd1b577125bb/src/Symfony/ConsoleApplicationResolver.php#L39

One way is to change the Symfony PHPStan to work with static reflection as the rest of PHPStan and Rector.
Another way is to have custom config for Rector, that only includes the static extensions. That's actually best practise, instead of including whole `phpstan.neon`.

I'll prepare PR to show what needs to be done.

**Comment by TomasVotruba** [comment]
There is the PR: https://github.com/alexander-schranz/rector-namespace-rename-reproducable/pull/2

I've added also PHPStan CI job, to make sure code is valid before running Rector. Code that crashes PHPStan will not likely work for Rector, so make sure the PHPStan always pass as success first.

As you can see, neither PHPStan can run, due to same issue of included files. The project is autoloaded because of console application factory, so any static reflection is killed.

**Comment by TomasVotruba** [comment]
I've proposed solution, as this is architecture bug in the extension package.

**Comment by alexander-schranz** [comment]
So if I'm understanding correctly to avoid the error when console application is used to detect the correct types. It would need a change in the symfony phpstan extension how the console.php is loaded here: https://github.com/phpstan/phpstan-symfony/blob/edb55af46fe1aaa62fafae51c36ccd1b577125bb/src/Symfony/ConsoleApplicationResolver.php#L39

Maybe we can ask @ondrejmirtes here about his opinion or thoughts about this.

**Comment by TomasVotruba** [comment]
> It would need a change in the symfony phpstan extension how the console.php is loaded here: phpstan/phpstan-symfony@edb55af/src/Symfony/ConsoleApplicationResolver.php#L39

Yes, exactly :+1:
