### ISSUE TITLE
Issues when converting annotations to php attributes

### ISSUE THREAD

**Issue by fabienlem** [rectorphp/rector#6848]
Hello there,

I tried to convert annotations to php8 attributes following this turorial: 
https://getrector.org/blog/how-to-upgrade-annotations-to-attributes

I ran into several issues:

- Empty lines are removeds in processed files (between class attributes and class methods)
- Some Doctrine related annotations are not converted, eg:

`@ORM\Table(uniqueConstraints={@ORM\UniqueConstraint(name="customer_idx", columns={"last_name", "first_name", "workspace_id"})})`

- Some routing related annotations are not converted, eg:

`@ParamConverter("date", options={"format": "Y-m-d"})`

Are there any additional settings to be made in the `rector.php` file?

Thank you a lot! 
Kind regards,

Fabien

**Comment by TomasVotruba** [comment]
H Fabien,

thanks for clear report.

1. The empty lines are sometimes side effect of AST transformation, as described in README - https://github.com/rectorphp/rector#how-to-apply-coding-standards. Be sure to use coding standard tool to match your needs. See `ecs.php` in our project for inspiration.

2. Nested attributes are only supported since PHP 8.1 and specific Symfony/Doctrine version. AFAIK the Doctrine did not released yet support for PHP 8.1 nested attributes. You'll have to wait for them to add it, then use propper Doctrine set.

3. If Rector would convert all annotation that exist to their attribute form, it might crash, as not all packages provide this form yet and some packages provide incompatible name of ctor arguments. Attribute upgrade is configured with generic rule. E.g. this one is for doctrine/orm 2.9 - https://github.com/rectorphp/rector-doctrine/blob/main/config/sets/doctrine-annotations-to-attributes.php You can either complete it manually to your `rector.php` as you say, or help others and extend the Symfony set version, that should include it. For Symfony, you can find configs here: https://github.com/rectorphp/rector-symfony/tree/main/config/sets

**Comment by samsonasik** [comment]
@fabienlem for removed empty lines on class property and class method, you can add back with `NewlineAfterStatementRector` rule.

You can add in the rector.php

```php
<?php

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // other config ... 

    $services = $containerConfigurator->services();
    $services->set(\Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector::class);
};
```

ref https://getrector.org/demo/1ec56953-7283-687a-9290-51ac3ebd72d2

**Comment by fabienlem** [comment]
Thank you both for your feedback!

**Comment by samsonasik** [comment]
I am closing as answered.

**Comment by TomasVotruba** [comment]
@fabienlem For point 3., this is how new set and configuration looks like :)
https://github.com/rectorphp/rector-symfony/pull/85

**Comment by fabienlem** [comment]
Thanks @TomasVotruba.

I succeed in convert annotations to php attributes on 2 of my projets with rector taking into account your feedback.

About unique constraint, I found out that Doctrine solved nested attributes issue by "spliting" attribute in two parts.

eg:

```
@ORM\Table(uniqueConstraints={@ORM\UniqueConstraint(name="customer_idx", columns={"last_name", "first_name", "workspace_id"})})
```

becomes:
```
#[ORM\Table]
#[ORM\UniqueConstraint(name: 'customer_idx', columns: ['last_name', 'first_name', 'workspace_id'])]
```

**Comment by TomasVotruba** [comment]
That was really the onl way untill PHP 8.1 allowed nested attributes - https://symfony.com/blog/new-in-symfony-5-4-nested-validation-attributes. I expect they'll follow the same features like Symfony did, as it's better for BC.
