### ISSUE TITLE
Incorrect behavior of ReturnTypeDeclarationRector

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#6852]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec58247-f7de-6f9e-8dd6-39bde39f72fc

```php
<?php

declare(strict_types=1);

/*
 * This file is part of the Serendipity HQ Stripe Bundle.
 *
 * Copyright (c) Adamo Aerendir Crespi <aerendir@serendipityhq.com>.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace SerendipityHQ\Bundle\StripeBundle\Dev\Helper;

use Doctrine\ORM\Mapping\ClassMetadataInfo;
use Doctrine\ORM\Mapping\MappingException;
use SerendipityHQ\Bundle\StripeBundle\Dev\Doctrine\MappingFilesLocator;

class MappingHelper
{
    /** @var \Doctrine\ORM\Mapping\Driver\XmlDriver|null */
    private static $driver;
    /** @var mixed[] */
    private static $cache = [];

    public static function getMappedProperty(string $localModelClass, string $property): ?array
    {
        try {
            return self::getMetadataInfo($localModelClass)->getFieldMapping($property);
        } catch (MappingException $mappingException) {
        }

        return null;
    }

    private static function getMetadataInfo($localModelClass): ClassMetadataInfo
    {
        if (false === isset(self::$cache[$localModelClass])) {
            $metadataInfo = new ClassMetadataInfo($localModelClass);
            self::getDriver()->loadMetadataForClass($localModelClass, $metadataInfo);
            self::$cache[$localModelClass] = $metadataInfo;
        }

        return self::$cache[$localModelClass];
    }
}
```

### Responsible rules

* `ReturnTypeDeclarationRector`

## Expected Behavior

Rector shouldn't change anything.

The full class is here: https://github.com/Aerendir/bundle-stripe/blob/dev/dev/Helper/MappingHelper.php

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

The code should be as minimal as possible.

**Comment by samsonasik** [comment]
@Aerendir that seems somehow `ClassMetadataInfo` not loaded early, I tried create in the demo and it seems working as expected,

see https://getrector.org/demo/1ec5b502-bff1-610c-a6e0-4963abf4e7de that the only changed is the `ClassMetadataInfo::getFieldMapping()` return type hint itself, which not has type hint previously, and in the position in vendor in real app, which not subject to change on your use case.

You may need to load early via register it in your composer.json's under "files" config, something like:

```javascript
    "autoload-dev": {
        "files": [
            "vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php"
        ]
    }
```
I used this trick when working with kahlan test framework on https://github.com/samsonasik/ErrorHeroModule/blob/c8596465729faab063a4c09d5ef2d7fd9514f12d/composer.json#L108 because it got class not found in Github Action, Yes, the issue only in Github Action only, not in my local dev.

Also, you may need to try `"rector/rector": "dev-main"` with set:

```bash
composer config minimum-stability dev

composer config prefer-stable true

composer update --dev rector/rector:dev-main
```
