### ISSUE TITLE
Incorrect behavior of RenameFunctionRector - mysql_query => mysqli_query

### ISSUE THREAD

**Issue by JaKopecky** [rectorphp/rector#6917]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec6ee71-f66e-6226-a594-edc2cd20a94c

```php
<?php

$sql_jazyk = mysql_fetch_array(mysql_query("SELECT * FROM jazyky WHERE id='".$vychozi_jazyk."'"));
```

### Responsible rules

* `RenameFunctionRector`

## Expected Behavior

Rector should change mysql_query to mysqli_query.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

The reason is the 1st argument needs to be filled with connection. Rector probably could not find connection above:
https://stackoverflow.com/questions/26476162/can-i-blindly-replace-all-mysql-functions-with-mysqli

```diff
-mysql_query("SELECT * FROM jazyky WHERE id='".$vychozi_jazyk."'")
+mysql_query($connection, "SELECT * FROM jazyky WHERE id='".$vychozi_jazyk."'")
````

In this case, either create connection above the function call or manualy update the line.

**Comment by TomasVotruba** [comment]
Closing as the 1st argument is needed manually in this case.
