### ISSUE TITLE
Contributor guidelines do not work

### ISSUE THREAD

**Issue by leighman** [rectorphp/rector#6994]
rector-src Commit c66771929ed316bac6b1191b287bd87f2be36865

When I run
```
docker-compose run php composer install
```
I get
```
  - Applying patches for symfony/dependency-injection
    https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/symfony-dependency-injection.patch (0)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/symfony-dependency-injection.patch
```
which seems to result in being unable to run phpunit tests

**Comment by leighman** [comment]
Ah, seems like `patch` is not available in the container

**Comment by TomasVotruba** [comment]
Thank you for the patch with `patch` :+1: 
Unfortunatelly, we cannot help with Docker, as we don't use it for development at all.

If you find a way to improve your issue, please send PR to handle it by default. Thank you

**Comment by leighman** [comment]
What's the point of suggesting it in the contributor guidelines then?

**Comment by TomasVotruba** [comment]
cc @Wirone https://github.com/rectorphp/rector-src/commit/2acce0ab9bca8ec596cece5f8c3d5e640d9e7d73

**Comment by Wirone** [comment]
@leighman you need to:

- ensure you have up-to-date Docker image (`docker-compose build`)
- ensure you have newest vendors (`docker-compose run php composer update`), since lock file is not provided by repo itself you need to follow packages by hand

@TomasVotruba but actually there's an issue because of missing `"enable-patching": true` in `extra` section of `composer.json`. Do you have it in your global Composer config? Maybe that's why it works for you 😉 When I added it and re-installed vendors the patch was applied and PHPUnit works (prints some noise like `! [NOTE] File "/tmp/_temp_fixture_easy_testing/names.json" will be added`, but works). I think patching should be enabled on repo level and it'll work.

**Comment by leighman** [comment]
@Wirone tests seem to be working after running those. thanks
