### ISSUE TITLE
PHPExcel to Spreadsheet adds redundant method value

### ISSUE THREAD

**Issue by milomylo** [rectorphp/rector#6997]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  0.12.16          |
| phpoffice/phpspreadsheet | 1.21             |

```diff
-            $sheet->getColumnDimension($column)->setWidth(20);
+            $sheet->getColumnDimension($column, true)->setWidth(20);
```

method [getColumnDimension](https://github.com/PHPOffice/PhpSpreadsheet/blob/b6bd822b9cd7c3578aea4b54226a565bb062c37f/src/PhpSpreadsheet/Worksheet/Worksheet.php#L1376) use 1 param:
```php
public function getColumnDimension(string $column): ColumnDimension
```

same problem with getCell:
```diff
-            $cell = $sheet->getCell("{$column}{$firstRowIndex}");
+            $cell = $sheet->getCell("{$column}{$firstRowIndex}", true);

```

## Expected Behaviour
without redundant `true` parameter.

**Comment by samsonasik** [comment]
That's possibly due to different version ,for example, in `phpoffice/phpspreadsheet` 1.17.1, the second arg is needed:

https://github.com/PHPOffice/PhpSpreadsheet/blob/c55269cb06911575a126dc225a05c0e4626e5fb4/src/PhpSpreadsheet/Worksheet/Worksheet.php#L1368

You may need to use rector `\Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector::class` rule to clean up it, 

ref https://getrector.org/demo/1ec8b072-9709-6d48-9cb0-857376608e92

with config:

```php
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
   // other config here 

    $services = $containerConfigurator->services();
    $services->set(\Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector::class);
};
```
