### ISSUE TITLE
Downgrade PHP 8.1: Enum

### ISSUE THREAD

**Issue by rvanlaak** [rectorphp/rector#7013]
# Feature Request

Downgrade PHP 8.1 Enum to an opinionated enum implementation. Or even better, would downgrading be possible without requiring an external dependency?
 
## Diff 

```diff
- enum Action : string
+ use MyCLabs\Enum\Enum;
+
+ final class Action extends Enum
-    case VIEW = 'view';
+    private const EDIT = 'edit';
```

And usage
```diff
-$name = SomeEnum::VALUE;
+$name = SomeEnum::VALUE()->getKey();
```

## Use case

Engineering wants to develop (and run CI) on PHP 8.1 and run production in PHP 8.0 (or lower) because several infra dependencies do not support 8.1 yet.

## Related to

* https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#myclabsclasstoenumrector
* https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#myclabsmethodcalltoenumconstrector

**Comment by TomasVotruba** [comment]
> Or even better, would downgrading be possible without requiring an external dependency?

That would be better solution, as external dependency might conflict with other dependencies in the project.
How would you downgrade those enums in your project using only PHP?

**Comment by ian-zunderdorp** [comment]
Suggestion: If it is relatively easy to implement the 'opinionated' way now by requiring a dependency, why not offer it as an option but not include it in the default downgrade lists? It does feel to me like this should be a Rector rule that is offered by a separate package rather than included with Rector by default, so it is not an immediate maintenance burden (and allows quicker iteration loops for Enum-specific feedback, as I figure there is a wide range of functionality bundled in the Enum implementation in PHP 8.1 which has exotic usecases).

**Comment by TomasVotruba** [comment]
>  It does feel to me like this should be a Rector rule that is offered by a separate package rather than included with Rector by default, so it is not an immediate maintenance burden.

I like this option :+1:

**Comment by rvanlaak** [comment]
So the question is whether it is even possible to downgrade PHP's enum implementation? Does it seem possible for enums without string as value?

```diff
- enum Language {
-    case EN_US;
+/**
+ * @method EN_US
+ */
+ class Language {
+    private string $value;
```

vs. with string as value


```diff
- enum Language: string {
-    case EN_US = 'en_us';
+ class Language {
+    private const EN_US = 'en_us';

**Comment by leoloso** [comment]
Having seen the availability of [`DowngradeEnumToConstantListClassRector`](https://github.com/rectorphp/rector-downgrade-php/blob/main/docs/rector_rules_overview.md#downgradeenumtoconstantlistclassrector), I attempted to add Enums to my code, with the intention to downgrade it to PHP 7.1.

Enums themselves are downgraded well. This code:

```php
enum Order: string
{
    case Asc = 'ASC';
    case Desc = 'DESC';
}
```

is successfully downgraded to:

```php
class Order
{
    public const Asc = 'ASC';
    public const Desc = 'DESC';
}
```

However, the references to the Enum are not being dealt with, then there is no point in using Enums, as the downgraded code will produce PHP errors:

- method `::cases()` (https://www.php.net/manual/en/unitenum.cases.php)
- properties `->name` and `->value` (for backed enums)

The following code should also be downgraded:

```php
$enumValues = array_map(
    fn (Order $order) => $order->value,
    Order::cases()
);
```

like this (or something like this):

```php
$enumValues = array_map(
    fn (string $order) => $order,
    [Order::Asc, Order::Desc]
);
```

I think that only once `DowngradeEnumToConstantListClassRector` also downgrades these references it will be feasible to use and downgrade Enums.

**Comment by TomasVotruba** [comment]
Yes, this rule needs much more work from someone who use enums actively.

**Comment by rvanlaak** [comment]
Would love to help!

**Comment by TomasVotruba** [comment]
This will require someone taking the time and effort and adding first rules to kick of the downgrade.

Closing as accepted to avoid keep issue tracker focus on unclear issues that needs our attention.
Feel free to send PR with it :+1:

**Comment by Wirone** [comment]
I understand this issue was closed due inactivity and lack of contribution, but I would like to point out the fact that `DowngradeEnumToConstantListClassRector` produces invalid code that leads to fatal errors. 

The availability of this rule is misleading, as it may look like it's possible to downgrade enums, but in reality it's not. Please consider reopening this, or at least [document this rule](https://github.com/rectorphp/rector-downgrade-php/blob/main/docs/rector_rules_overview.md#downgradeenumtoconstantlistclassrector) as incomplete and risky 😊. In practice, enums can't be used in projects that use downgrading, which is a pity as it is excellent PHP8 feature.

Code like this:

```php
enum Dictionary: string
{
    case Foo = 'foo';
    case Bar = 'bar';
}

function foo(Dictionary $dictionary): void
{
    echo $dictionary->value;
}

foo(Dictionary::Foo);
```

should be downgraded to:

```php
class Dictionary
{
    public const Foo = 'foo';
    public const Bar = 'bar';
}

/**
 * @param Dictionary::* $dictionary
 */
function foo(string $dictionary): void
{
    echo $dictionary;
}

foo(Dictionary::Foo);
```

Instead, the result is:

```php
class Dictionary
{
    public const Foo = 'foo';
    public const Bar = 'bar';
}

function foo(Dictionary $dictionary): void
{
    echo $dictionary->value;
}

foo(Dictionary::Foo);
```

Running such code results in `Fatal error: Uncaught TypeError: Argument 1 passed to foo() must be an instance of Dictionary, string given`.

Thank you very much in advance for taking your time on it!
