### ISSUE TITLE
TypedPropertyRector creates a ?mixed property

### ISSUE THREAD

**Issue by greg0ire** [rectorphp/rector#7200]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/c09a2aec-5578-454e-9afe-80e0f7c0a0fb

```php
<?php

declare(strict_types=1);

namespace Doctrine\Tests\ORM;



class NotifyChangedEntity
{


    /** @var mixed */
    private $transient; // not persisted


    public function setTransient($value): void
    {
        if ($value !== $this->transient) {

        }
    }
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

Rector should use `mixed` here, not `?mixed`, which causes a crash: https://3v4l.org/v4KkO

**Comment by samsonasik** [comment]
It should be skipped instead as we skip mixed type itself for complex usage on TypedPropertyRector 

https://github.com/rectorphp/rector/blob/532e6c65bdafe754751f7a4770edcb952819f04e/rules/Php74/Rector/Property/TypedPropertyRector.php#L149

The change seems due to nullable mixed, which should not allowed.
