### ISSUE TITLE
AnnotationToAttributeRector does not work for nested aliased annotations

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#7368]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.10             |

Does **not** work:
```php
use App\Validator\Constraints as AppAssert;

class MyClass
{
    /**
     * @AppAssert\User\SomeUserAssert
     */
    private $field;
}
```
Does work:
```php
use App\Validator\Constraints\User as AppAssertUser;


class MyClass
{
    /**
     * @AppAssertUser\SomeUserAssert
     */
    private $field;
}
```

**Comment by TomasVotruba** [comment]
Thank you for your report.

We'll need a failing test case in a pull-request, so we have it covered in Rector in isolated context.

**Comment by TomasVotruba** [comment]
By convention, we require the reproducible test PR that shows the exact problem. We have lot of work with maintaining this open-source project, so we ask the contributors to help us out :) 

From your report, it's not clear what exact rule setup causes what error. We can discuss about it few days, but test fixture proves it once and for all. It's not uncomon the report is false positive, e.g. due to missing class or wrong autoload. 

With reproducer, we can fix the problem much faster and higher volume. If you're not willing to contribute, it's ok. Maybe somebody will pick it up later.

**Comment by TomasVotruba** [comment]
Thanks. The annotation class must exist, otherwise the matching can see it as a string and skip it.

The test fixture should be located here:
https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture

Easies way is to copy existing file and change the contents. If you use existing annotation class, you can add just the test fixture file.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:

Thank you for understanding :slightly_smiling_face:
