### ISSUE TITLE
AddReturnTypeDeclarationRector can't change return type to nullable return type

### ISSUE THREAD

**Issue by owsiakl** [rectorphp/rector#7395]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.10             |

Looks like when we try to change return type to nullable return type, it skips the change.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/45f677a9-fbb5-4edf-a460-5eea59e36247.

```php
<?php

final class DemoFile
{
    public function getSomething() : string
    {
        return null;
    }
}
```
```php
<?php

use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\ClassMethod\AddReturnTypeDeclarationRector;
use Rector\TypeDeclaration\ValueObject\AddReturnTypeDeclaration;
use PHPStan\Type\StringType;
use PHPStan\Type\UnionType;
use PHPStan\Type\NullType;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(AddReturnTypeDeclarationRector::class, [
        new AddReturnTypeDeclaration(
            DemoFile::class,
            'getSomething',
            new UnionType([new NullType(), new StringType()])
        ),
    ]);
};

```

## Expected Behaviour

`string` return type should be changed to the `?string` one.

**Comment by owsiakl** [comment]
BTW, there is already a fixture for it, but I'm not sure that this should be an expected behaviour. Looks like it was implemented for a specific use case.
https://github.com/rectorphp/rector-src/blob/main/rules-tests/TypeDeclaration/Rector/ClassMethod/AddReturnTypeDeclarationRector/Fixture/skip_implements_nullablestring_already_has_type.php.inc

**Comment by TomasVotruba** [comment]
This is skipped on purpose, to allow more precise types by user-defined types:
https://github.com/rectorphp/rector-src/blob/c4d6f19b4d6386758b1f7aee3f1a9d4e41b59b42/packages/VendorLocker/ParentClassMethodTypeOverrideGuard.php#L148

Otherwise e.g. Symfony return types put nullable everywhere, just because it can be also nullable, if not defined. That would break the type reliability in the project.


What is your exact use case? Seems the input code is not even valid and would crash.

**Comment by owsiakl** [comment]
Yea, this was just a minimal example. 
We have a code generation tool that is taking return type from the schema that we don't own. This return type is sometimes incorrect and we want to fix it after code is generated.

Although I think that the code that you highlighted passes because return type in our case is not null. Can it be related to this part?  https://github.com/rectorphp/rector-src/blob/main/packages/NodeTypeResolver/TypeComparator/TypeComparator.php#L124, which in case of [UnionType](https://github.com/phpstan/phpstan-src/blob/1.8.x/src/Type/UnionType.php#L149) is returning bool, cuz there as a logical `OR` operator inside.

**Comment by TomasVotruba** [comment]
> We have a code generation tool that is taking return type from the schema that we don't own. This return type is sometimes incorrect and we want to fix it after code is generated.

I see. In that case would be better to encorporate this logic to the generator. If you already have AST, it's few lines to add this type.

> Although I think that the code that you highlighted passes because return type in our case is not null.

The linked code skips the type because the return type declaration is already there.
If is not filled, it will complete the type you've provided: https://getrector.org/demo/6179a7dc-63d4-478a-97f5-8996bf9eb350

**Comment by TomasVotruba** [comment]
Saying that, this feature has to remain as it is, to avoid changing more precise user defined type.
