### ISSUE TITLE
Incorrect behavior of AddArgumentDefaultValueRector, ChangeSwitchToMatchRector, RenamePropertyRector

### ISSUE THREAD

**Issue by ImJustToNy** [rectorphp/rector#7478]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/eacabd45-763b-4ff0-95ec-ae3e247ca1c7

```php
<?php

final class DemoFile
{
    private function price_action_by_server_name($price, $server)
    {
        $factor = 1.0;
        switch ($server->name) {
            case 'a':
                $factor = 0.95;
                break;
            case 'b':
            case 'c':
                $factor = 0.8;
                break;
            case 'd':
            case 'e':
                $factor = 0.8;
                break;
            case 'f':
                $factor = 0.7;
                break;
        }

        return $price * $factor;
    }
}
```

### Responsible rules

* `AddArgumentDefaultValueRector`

* `ChangeSwitchToMatchRector`

* `RenamePropertyRector`

## Expected Behavior

Rector decided to guess `default` for match, but it broke down the logic, since `$price`  is multiplied by `$factor` twice. IMHO it should be:
```php
<?php

final class DemoFile
{
    private function price_action_by_server_name($price, $server)
    {
        $factor = match ($server->name) {
            'a' => 0.95,
            'b', 'c' => 0.8,
            'd', 'e' => 0.8,
            'f' => 0.7,
            default => 1.0,
        };

        return $price * $factor;
    }
}
```

**Comment by samsonasik** [comment]
@ImJustToNy it seems because of `ChangeSwitchToMatchRector` rule, ref https://getrector.org/demo/5d3366ee-9990-43af-9c0e-0cb49f8f9f82

On that case, that seems should be skipped, could you provide failing test case for that and possibly make a patch? 

The steps can be:

1. Add Failing fixture to https://github.com/rectorphp/rector-src/tree/73aa7e3d68d74fc0b9b26fc543bf1207cfc8d0dd/rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture , You can copy other fixture with `skip_` prefix for fixture that need to be skipped.
2. Run test : 

```bash
vendor/bin/phpunit rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/ChangeSwitchToMatchRectorTest.php
```

3. Provide a patch, it seems bug on `MatchSwitchAnalyzer` https://github.com/rectorphp/rector-src/blob/73aa7e3d68d74fc0b9b26fc543bf1207cfc8d0dd/rules/Php80/NodeAnalyzer/MatchSwitchAnalyzer.php#L71
