### ISSUE TITLE
Disable rector rule for 1 place in file only?

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7679]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15             |

0.15 removed @noRector annotation - while there is the option to skip a whole file via the config, how do you handle cases where a rule should only be ignored in 1 line of the file?

e.g. I have 1 line in the file where I want to ignore `RenameVariableToMatchMethodCallReturnTypeRector`
All other places in the file should still be fixed by this rule. How is this supposed to work now?

## Minimal PHP Code Causing Issue

```
$foo = new Bar();
```

## Expected Behaviour

Option to ignore rector rule for this line.

**Comment by TomasVotruba** [comment]
Hi, the feature is not available any more. It was removed, because it added silent ignores that were missed later.
It also allowed too detailed ignores and "tool programming" in the code, like you described.

You can ignore the whole file: https://getrector.org/documentation/ignoring-rules-or-paths
But in this case I'd go with type update, to make the code consistent.

**Comment by jorismak** [comment]
get instances now where PHPStan knows the type is an array of objects (returned from a doctrine queryBuilder `->getQuery()->getResult()`).

But rector changes the line to a `is_countable($var) ? count($var) > 0 : 0`. Then phpstan goes complaining that the ternary check is always true.

So rector seems to think the variable can be array of null, while phpstan (checked with dumpTyoe) thinkgs it's for sure an array.

So I need to ignore phpstan rules, or remember to not commit that one line that rector always wants to do.

This seems like a valid use case to prevent rector from changing a certain part of the file. Yes I can skip that rule in that file, but there are other places where it was doing things OK.

**Comment by DieterHolvoet** [comment]
I agree, in the real world Rector rules don't always work exactly as they should and opening issues with test cases to reproduce is just not always possible, it takes a lot of time. Ignoring a rule for a certain line is a necessary feature, one that most other tools offer as well. Removing @noRector annotations for lines where they don't apply anymore is the responsibility of the user and not really a problem for the Rector package maintainer, or am I wrong?

**Comment by TomasVotruba** [comment]
@jorismak Thanks for reporting :+1:  

> So rector seems to think the variable can be array of null, while phpstan (checked with dumpTyoe) thinkgs it's for sure an array

This should definitely work, as we only take over PHPStan types. Could you add a failing test fixture with your use case?

**Comment by rmobis** [comment]
I know this is an old issue, but I wanted to echo the feeling that being able to ignore specific rectors in specific lines is essential. Very often it is not in our control to make the appropriate corrections and being forced to disable the rule in the entire file just decreases the value PHP Rector provides, while not really making it any easier not to "miss the ignore later".

Actually, I would argue it makes it harder, because when it's tied to a specific line I can very easily see why it's needed and reason whether it can now be removed or not, while when it's specified in the config and forced on an entire file I loose the entire context. The appropriate solution here would be to error on `@noRector` directives that are not actually needed, which is the behavior of pretty much every other static analysis tool.

To give a little more context, this is the situation I'm currently facing, but I've had other issue:

My code depends on another package and one of the methods from this package returns `string`. They announced a breaking change soon to be implemented where the return type will be changed to `?string`. To future-proof my code, I have already added a `if ($obj->method() !== null)` check. PHP Rector obviously doesn't like that because, for current types, this is always true so it triggers `RemoveAlwaysTrueIfConditionRector`. Disabling the rule (globally or in this file) just means I'm potentially missing unknown issues in other parts of the code.

**Comment by alessandro-podo** [comment]
I would also like to see a way to ignore some lines.

**Comment by pau1phi11ips** [comment]
I would also like to see a way to ignore some lines.

**Comment by samsonasik** [comment]
@kkmuffme please don't spamming, it documented that rector may cause drawback on mix php+html https://github.com/rectorphp/rector?tab=readme-ov-file#known-drawbacks
