### ISSUE TITLE
importNames should add use statements after existing not before

### ISSUE THREAD

**Issue by kkmuffme** [rectorphp/rector#7738]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.8             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/474cdaee-4a78-40b1-9c76-3b534f3482ef

When a file is namespaced this isn't an issue, since the filedoc is usually above the namespace:
https://getrector.com/demo/1cefb7dd-458c-46ba-8aff-4f36b82f4cf4

## Expected Behaviour

Any new/additional "use" statements should be added AFTER the already existing ones, not before them.
Otherwise this often creates bad readability with filedoc comments.

**Comment by samsonasik** [comment]
The issue is not about add after, add before is fine since  namespaced file doesn't has issue of it since it has mirror comment handling

https://getrector.com/demo/d2de82ef-d14b-4eae-b91b-b3ebe2cd3cd9

Ref https://github.com/rectorphp/rector-src/blob/1142c99af7380356e2d1c8e572fb6d19830db51f/rules/CodingStyle/Application/UseImportsAdder.php#L99-L111

while no-namespace file doesn't https://github.com/rectorphp/rector-src/blob/1142c99af7380356e2d1c8e572fb6d19830db51f/rules/CodingStyle/Application/UseImportsAdder.php#L34-L68

So, the mirror comment should be applied on no-namespace as well for this case.
