### ISSUE TITLE
bc break preserving

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#7837]
# Feature Request

I think it would be great if rector would have a config which allows the user to express that we are only interessted in non-BC breaking changes.

when this switch is enabled a rule like e.g. `ReturnTypeFromStrictTypedCallRector` could then only do its magic for private methods or protected methods of final classes.

wdyt?

**Comment by samsonasik** [comment]
On some rule, there is `INLINE_PUBLIC` configurable, eg, on `TypedPropertyFromAssignsRector`, which default to `false` with change:

- private modifier property
- protected modifier property on final class without extends or has extends but property and/or its usage only in current class

Set to `true` will allow change other modifiers as well as far as not forbidden:

https://github.com/rectorphp/rector-src/blob/c240c69f45c29685eeace5ad0737ef049dff5211/rules/TypeDeclaration/Rector/Property/TypedPropertyFromAssignsRector.php#L31-L45

**Comment by staabm** [comment]
My idea is more about developer experience as a whole, for the very first steps one needs to take to get higher type coverage in component projects where you cannot change public symbols because this would need changes in consuming projects. 

Its not about enabling feature switches on a per rule basis but similar to e.g. php target version, where one defines globally for multiple rectors that they should not touch code which might break consuming code (as a safety step to increase type coverage in the first place, without manual intervention)

**Comment by TomasVotruba** [comment]
This mostly depends on many factors we cannot influence:

* is the codebase package or project?
* are BC breaks intentional to raise code-quality or not?
* is it used as open-source or internally in private project?

I was thinking about putting few limitations into the Rector configuration at the very start, but it created huge complexity, if/else conditions in many rules and in some cases, lead to missunderstanding of rules.

Instead of making Rector more complex, this descission is up to the developer of each particular project to meet their specific needs. Using rules(), sets(), skip() and phpVersion() to tailor the expected output.

**Comment by staabm** [comment]
thx for the in-detail answer. since I am using rector more and more, I can agree with it.
