### ISSUE TITLE
Parameter's name changed during inheritance

### ISSUE THREAD

**Issue by beeyev** [rectorphp/rector#7879]
For example, I have some interface in `vendor` dir:
```php
interface ExceptionHandler
{
    public function render($request, Throwable $e);
}
```

And I have a custom class implementing this interface. 
After I applied Rector with  `RenameParamToMatchTypeRector`, i get this result:
```php
class Handler implements ExceptionHandler
{
    public function render($request, \Throwable $throwable) // variable was renamed by Recotor from $e to $throwable
    {
 		...
    }
}
```

I think Rector should not rename parameters that were defined in parent class that is not accessible for changes.
Otherwise, it causes a warning 
![image](https://user-images.githubusercontent.com/326840/232253930-84557ef9-4b3a-4e34-92a5-71ea55088429.png)

PHPStorm [Code Inspection](https://www.jetbrains.com/help/phpstorm/php-parameter-s-name-changed-during-inheritance.html) says that Starting with PHP 8.0, such code can cause runtime errors.

**Comment by staabm** [comment]
Could you come up with a reproducing example in https://getrector.com/demo or at best a unit test?

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. 

This is expected behavior of this rule as it's goal to make naming and types compatible, to avoid using `$e` anywhere in the code. If it contradicts contract in vendor, you can skip this rule or better improve the naming in the open-source package.

Thanks for understanding :+1:
