### ISSUE TITLE
Add DeMorgan simplify Rector

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#797]
To prevent `!($anything !== false)`. Maybe create a new Rector

```diff
-!($a === null || $b < $c);
+$a !== null && $b >= $c;
```

```diff
-!(!$a || $b !== $c);
+$a && $b === $c;
```

```diff
-!($a > $b || $c <= $d)
+$a <= $b && $c > $d
```

**Comment by TomasVotruba** [comment]
The same case

```diff
                if (!$calling_context || $appearing_method_class !== $calling_context) {
                    return false;
                }
                 return true;
                return $calling_context && $appearing_method_class === $calling_context;

```

**Comment by TomasVotruba** [comment]
Do you know about some generic approach to binary inversions?
/cc @mssimi @nikic @fprochazka

**Comment by nikic** [comment]
Generic approach would be to recursively apply De Morgan's laws to !(&&) and !(||) and use inverted predicates for comparison operators. Which seems to be pretty much what your examples are already doing.

A note of caution though. For floating point comparisons there is a distinction between ordered and unordered comparisons and notably, the inverse predicate for an ordered comparison will be an unordered comparison and vice-versa. For example the inverse of ordered lower equal is unordered greater than (`not ole == ugt`), not ordered greater than.

This distinction is only important if one of the inputs to the comparison may be `NaN`. As a practical example:

    $a = NAN;
    $b = NAN;
    var_dump(!($a > $b)); // bool(true)
    var_dump($a <= $b)); // bool(false)

Floating points are just one example of this issue, it also exists for other cases which are only partially, rather than totally ordered. As PHP does not allow userland overloading of comparison operators, this is not very common, but it can happen with some internal classes.

Whether or not you want to care about such issues is for you to decide :) A source code transformer can usually take more liberties with technically incorrect transformations than a compiler ;)

**Comment by TomasVotruba** [comment]
@nikic Thanks you for these insights :+1: , that's exactly what I needed. I'll investive your leads :)

I didn't know about the floating points issue. So far all conditions refactored this way were much more simple, but I'll keep that in mind.
