### ISSUE TITLE
Incorrect behavior of LocallyCalledStaticMethodToNonStaticRector

### ISSUE THREAD

**Issue by toastedghost** [rectorphp/rector#7992]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.17.1, last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a94fe4b3-0e91-4aa2-b298-4ec49c34b32f

```php
<?php

final class DemoFile
{
    public function run(string $var): bool
    {
        $checkRes = self::check($var);
        
        return $checkRes;
    }
    
    private static function check($value): bool
    {
        return true;
    }
}
```

### Responsible rules

* `LocallyCalledStaticMethodToNonStaticRector`

## Actual Behavior
```php
public function run(string $var): bool
     {
-        $checkRes = self::check($var);
+        $checkRes = $this->check();
         
         return $checkRes;
     }
     
-    private static function check($value): bool
+    private function check($value): bool
     {
         return true;
     }
```

## Expected Behavior
```php
public function run(string $var): bool
     {
-        $checkRes = self::check($var);
+        $checkRes = $this->check($var);
         
         return $checkRes;
     }
     
-    private static function check($value): bool
+    private function check($value): bool
     {
         return true;
     }
```

**Comment by samsonasik** [comment]
@toastedghost could you try provide a patch for it? You can do with the following steps:

1. Add failing fixture under Fixture directory https://github.com/rectorphp/rector-src/tree/main/rules-tests/RemovingStatic/Rector/ClassMethod/LocallyCalledStaticMethodToNonStaticRector/Fixture

2. Provide a patch, it should be because the argument is not mapped, should be by change:

```diff
-return new MethodCall(new Variable('this'), $classMethodName);
+return new MethodCall(new Variable('this'), $classMethodName, $node->args);
```

at https://github.com/rectorphp/rector-src/blob/fb327f2b85a05597b4505321887720febd99de3d/rules/RemovingStatic/Rector/ClassMethod/LocallyCalledStaticMethodToNonStaticRector.php#L139
