### ISSUE TITLE
Constructor arguments condensed into a single line

### ISSUE THREAD

**Issue by carbsrule** [rectorphp/rector#8021]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.1             |

When Rector affects a constructor which has arguments spread over multiple lines, it condenses the arguments into a single line. This can be problematic in terms of readability as well as violating code standards on line length.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/532845df-5a8c-4c4b-8b60-2283d069a1e8

(The result is the same whether targeting PHP 8.1 or 8.2)

## Expected Behaviour

Leave the arguments spread over multiple lines, e.g.

```
public function __construct(
    private readonly LongClassNameUsedAsArgument $a,
    private readonly LongClassNameUsedAsArgument $b,
    private readonly LongClassNameUsedAsArgument $c,
) {
}
```

**Comment by samsonasik** [comment]
That's expected. You can use coding standard for that, see 

https://github.com/symplify/coding-standard/blob/7e50b0bb07d606074807f9fcdce33f26b3f19219/src/Fixer/Spacing/StandaloneLineConstructorParamFixer.php#L23

**Comment by PatchRanger** [comment]
Thanks for the answer. Looks like it doesn't work^ I can't include this fixer as Rector-fixer, because it doesn't have `RectorInterface` (though it implements `DocumentedRuleInterface` which is almost the same, `RectorInterface` is only a mark - but it breaks my try to enable it).
Also I can't extend this fixer to make it `implements RectorInterface` to pass as a rector - because this fixer is `final`.
Looks like this fixer is only usable together with ecs - and is not intended to use with Rector?
