### ISSUE TITLE
Code Quality vs Upgrade rules

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector#8045]
# Feature Request

As currently there is work done for rector 1.0. I want to open a discussion about the rules and where they belong to.

There are currently some rules in the UPGRADE process which I personally think should also be part of the `Quality` ruleset.

E.g.: `StrContainsRector::class, StrStartsWithRector::class, StrEndsWithRector::class, ...`

From PHP 8.0 upgrade.

https://github.com/rectorphp/rector/blob/dbd0b13b4fe1787c04ae4732e3d54310bdc0c22b/config/set/php80.php#L31

Technical I'm not even sure if they should even be part of the `upgrade` why it doesn't hurt, from technical point of view ststr, strpos, ... aren't deprecated and maybe should more be part of code only quality rules. But thats not what is important for me more about the usecase what should be part of the `SetList::CODE_QUALITY` if for example for performance reasons the `LevelSetList::UP_TO_PHP_82` is not activated. Think there would still be some rules which make sense be part of both SetLists like the above mention str functions.

**Comment by TomasVotruba** [comment]
Hi, I get your point many rules are useful whether you upgrade or not :) better code quality can be achieved even on lower PHP versions.

The reason to make sets exlusive, is to keep clear border and make them idempotent. Ideally no rule should be repeated in more than 1 set, so if you include all the basic ones, you run ever rule once. That's why most of PHP-related rules are not repeated anywhere else.

As for performance reasons, the most heavier part of Rector is parsing the code and traversing everynode. So enabling/disabling 50 rules does not make difference.

Take local `rector.php` for inspiration.
