### ISSUE TITLE
Incorrect behavior of ReadOnlyClassRector

### ISSUE THREAD

**Issue by fvozar** [rectorphp/rector#8058]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/e997b6f2-3398-44a6-a278-b7f04b034705

```php
<?php

class A {}


class B extends A
{
    
    public function __construct(
        private string $foo
    ) {}
    
    public function run()
    {
        return $this->foo;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`
* `ReadOnlyClassRector`
* `FinalizeClassesWithoutChildrenRector`

### Result from Rector

```diff
- class B extends A
+ final readonly class B extends A
```

## Expected Behavior

Class B shouldn't be `readonly` because PHP throws a "Fatal error:  Readonly class  B cannot extend non-readonly class A".

**Comment by dkarlovi** [comment]
FWIW, same problem with Symfony controllers extending from AbstractController.

**Comment by samsonasik** [comment]
@TomasVotruba the `$scope->getClassReflection()` on `Class_` somehow gone on multiple rules, probably due to context fill on `PHPStanNodeScopeResolver`;

https://github.com/rectorphp/rector/blob/22756db41317ebfeae63121a74c1d2b2646cf538/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php#L401-L405

so it got null after passed.
