### ISSUE TITLE
DowngradePureIntersectionTypeRector does not downgrade correctly

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#8086]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.7        |

The resulting PHPDoc is not correct regarding to namespace and uses.

It should be `\PHPStan\Parser\Parser` but it's `PHPStan\Parser\Parser`.

See the wrong transformation as diff here: https://gist.github.com/ondrejmirtes/6b92eb434fb7b4accfc6be576ea4b08e/revisions

## Minimal PHP Code Causing Issue

```php
private function getParserMock(): Parser&MockObject
```

## Expected Behaviour

```php
	/**
  * @return (Parser & MockObject)
  */
 private function getParserMock()
```

or

```php
	/**
  * @return (\PHPStan\Parser\Parser & \PHPUnit\Framework\MockObject\MockObject)
  */
 private function getParserMock()
```

## Actual Behaviour

```php

	/**
  * @return (PHPStan\Parser\Parser & PHPUnit\Framework\MockObject\MockObject)
  */
 private function getParserMock()
```

**Comment by samsonasik** [comment]
@TomasVotruba the updated fixture on commit https://github.com/rectorphp/rector-downgrade-php/commit/e72d49309c6e2b488d563126e2fc34b193d2f9a2#diff-f38988a031bf24e97c3d87001cf2d59dbbfd287cac75f445c967fe450ef7f379 seems the invalid.

It seems due to intersection type mapper update on PR:

- https://github.com/rectorphp/rector-src/pull/4572

due to `toPhpDocNode()` usage.
