### ISSUE TITLE
Infer native return type from ternary

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8089]
# Feature Request

I would expect one of the rules out of `SetList::TYPE_DECLARATION` would infer a native return type in https://getrector.com/demo/0e4a125c-bfa3-41fa-9b96-2af05c0f10a0

I guess it would be the job for `ReturnTypeFromStrictNativeCallRector` ?

**Comment by samsonasik** [comment]
`ReturnTypeFromStrictNativeCallRector` seems on direct return:

https://getrector.com/demo/eb454d73-fc70-4bc0-9814-13571efcd8d1

it seems doesn't support union type:

https://getrector.com/demo/962e801c-f543-4f1a-8347-c46c83a11edd

**Comment by staabm** [comment]
I will have a look, thx

**Comment by samsonasik** [comment]
@staabm it possibly union restriction is due to possible void, something like issue that created by @bloep at:

- https://github.com/rectorphp/rector/issues/7943

that resolved by Union type check at PR:

- https://github.com/rectorphp/rector-src/pull/3890

that unrelated rules, but possibly the reason.

**Comment by staabm** [comment]
I had a quick look but did not you find a way to correctly determine the proper return type for the given scenario
