### ISSUE TITLE
Incorrect behavior of AddParamTypeFromPropertyTypeRector

### ISSUE THREAD

**Issue by jlherren** [rectorphp/rector#8092]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/40eda128-4418-48ca-8e52-75b0894b43e2

```php
<?php

final class DemoFile
{
    private array $array = [];
    
    /** @param array|null $arrayOrNull */
    public function __construct($arrayOrNull) {
        if ($arrayOrNull !== null) {
            $this->array = $arrayOrNull;
        }
    }
}
```

### Responsible rules

* `AddParamTypeFromPropertyTypeRector`

## Expected Behavior

No change.

**Comment by samsonasik** [comment]
as the assign is under if, it may be tricky to handle, as if we check the type, it already array, also will come to another issue as if cond can be vary, I think the solution is to make the coalesce check instead, eg:

```php
$this->array = $arrayOrNull ?? [];
```

so that will be skipped, ref

https://getrector.com/demo/11e42b87-4ed3-4c6e-8be1-4dcf4c280757
