### ISSUE TITLE
missing array return type

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8187]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/01645249-c2f2-43b7-9254-352b703ac588

## Expected Behaviour

I think one of the rules in `\Rector\Set\ValueObject\SetList::TYPE_DECLARATION` should be able to infer a `array` return type - **no matter whether the classes involved are autoloadable or not.**

**Comment by samsonasik** [comment]
@staabm that seems due to abstract class, using non-abstract class add the return type https://getrector.com/demo/87bf8c02-b481-4177-b596-fd74970fb2bd

adding return type to method in abstract class may probably need check, due to extended uses no-return type, while that probably already covered by `AddReturnTypeDeclarationBasedOnParentClassMethodRector`

**Comment by samsonasik** [comment]
that seems expected, add return type to abstract class may cause multiple return definition in child, like in rector itself on using interface (similar condition):

https://3v4l.org/JLchd
