### ISSUE TITLE
Add support for downgrading return type null

### ISSUE THREAD

**Issue by RikudouSage** [rectorphp/rector#8324]
# Feature Request

PHP 8.2 allows `null` to be used as a standalone return type.
 
## Diff 

Use case 1, without parent:

```diff
<?php

class WithoutParent
{
+    /**
+     * @return null
+     */
-    public function getSomething(): null
+    public function getSomething(): mixed
    {
    }
}

```

Use case 2, with a parent:

```diff
<?php

class ParentClass
{
    public function getSomeString(): ?string
    {
    }
}

class ChildClass extends ParentClass
{
+    /**
+     * @return null
+     */
-    public function getSomeString(): null
+    public function getSomeString(): ?string
    {
    }
}
```

**Comment by TomasVotruba** [comment]
Hi, thanks for proposal. We actually don't support docblock-based types since Rector 0.15 https://getrector.com/blog/new-in-rector-015-complete-safe-and-known-type-declarations as it lead to false positive and breaking code in the past. 

We infer return/param/property type declarations from the code itself instead as the only safe way.

Use the TYPE_DECLARATIONS set instead :+1:

**Comment by RikudouSage** [comment]
How does that help? This is a downgrade rector that downgrades unsupported features from php 8.2. Meaning if someone imports the downgrade set, it should downgrade everything it can to supported syntax.

**Comment by TomasVotruba** [comment]
Ah, I confused the change other way around, my bad.

That would be great addition. Could you open up PR?

**Comment by samsonasik** [comment]
I will try

**Comment by samsonasik** [comment]
I created PR:

- https://github.com/rectorphp/rector-downgrade-php/pull/208

for it.
