### ISSUE TITLE
Rector has become very slow after upgrading from "0.12.17" to "1.0.2"

### ISSUE THREAD

**Issue by AHaydar** [rectorphp/rector#8523]
# Question
When on version 0.12.17, rector used to take 4 minutes to run against ~2000 PHP files.
I upgraded Rector to  1.0.2, and spent the time to change all of the configuration I have in my repo. Now, Rector is taking 12 minutes to run against the same ~2000 files.

I followed the steps mentioned [here](https://getrector.com/documentation/troubleshooting-parallel) to identify if it's a single file that's causing this issue - so I ran it with `disableParallel` and waited until all of the files were processed, but none got stuck or resulted in errors. The process does time out if I pass a `$seconds` less than 180 seconds. I tried different `maxNumberOfProcess` and `jobSize` and still have the same slowness.

Having to wait 12 mins as part of CI isn't a suitable option (currently only running rector against changed files to overcome the issue). Any suggestions would be appreciated.

**Comment by samsonasik** [comment]
we have a project with 4000+ files with many huge files and it only take 5 minutes, On CI, the slowness usually due to swap, I think you can configure jobs if you have file with large content, eg:

```php
$rectorConfig->parallel(240, 8, 8);
```

Reduce the jobSize argument usually make it faster for limited resource since it is a total files on hold on each process which require RAM before it quit and continue to next process.

Also, avoid using SetList you no longer needed, eg, you already upgraded until phpunit 10, you no longer need import PHPunit Setlist 6.0, etc

This post may help https://getrector.com/blog/5-common-mistakes-in-rector-config-and-how-to-avoid-them
