### ISSUE TITLE
Rule to convert "@param int|null $param" to "function method(?int $param)"

### ISSUE THREAD

**Issue by MagePsycho** [rectorphp/rector#8623]
Hello rector users,

I am struggling to find the `rectorphp` rule that converts the following code:
```
   /**
    * @param int|null $storeId
    */
    public function getBaseUrl($storeId = null): string
    {
        return $this->storeManager->getStore($storeId)->getBaseUrl();
    }
```
to
```
    public function getBaseUrl(?int $storeId = null): string
    {
        return $this->storeManager->getStore($storeId)->getBaseUrl();
    }	
```
	
FYI, I am using `LevelSetList::UP_TO_PHP_81`

**Comment by samsonasik** [comment]
If the `getStore()` method already param type hinted, it will converted with `typeDeclarations` set, see https://getrector.com/demo/7ae2d2a6-2697-4c30-b04b-54ed12d824c7

**Comment by samsonasik** [comment]
Update protected property may cause BC break on child classes, that's why it disabled by default, you can either make it private first:

https://getrector.com/demo/1a5cc52e-b860-434e-b4d2-805f57df040e

of use `TypedPropertyFromAssignsRector` configurable inline public:

https://getrector.com/demo/a55f7384-e2b1-412e-9038-650537961e4f

with beware: it may cause bc break. You can learn configurable example on the rule itself

https://github.com/rectorphp/rector/blob/87c26777cb60253826c3552c8a7a0b143224e7f9/rules/TypeDeclaration/Rector/Property/TypedPropertyFromAssignsRector.php#L129

**Comment by samsonasik** [comment]
You may have the target `getStore()` method on `MyOtherClass` not typed hint, eg: by docblock, we mostly don't convert docblock to type hint as by assumption.

When you want to be typed hinted, the `MyOtherClass::getStore()` need to have param type hint in the first place so the caller must be typed hint as well.

see again my original example https://getrector.com/demo/7ae2d2a6-2697-4c30-b04b-54ed12d824c7
