### ISSUE TITLE
Features removed in a patch version

### ISSUE THREAD

**Issue by BenMorel** [rectorphp/rector#8825]
Hi, we've been hit by the removal of `*ToTypeCastRector` rules, and were surprised to see that they've been removed in a patch release (`1.2.5`).

We're using an auto-upgrade tool ([Renovate](https://www.mend.io/renovate/)), and usually expect patch version upgrades to not break things, and always pass CI.

Does this project follow semver, or does it follow another convention? Is this documented?

Thank you.

**Comment by TomasVotruba** [comment]
Hi, these rules were deprecated for couple months now.
We remove deprecated rules more often, not waiting for BC version. 

The reason is to avoid promoting invalid patterns, like in case of these rules. The original motivation was to speedup code run, while in practice these was no significant difference.

I recommend subscribing to releases on `rector/rector` to stay up to date with changelogs.
