### ISSUE TITLE
Wrong version reported in --version

### ISSUE THREAD

**Issue by thePanz** [rectorphp/rector#8946]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 2.0.1 (according to `rector --version`             |

## Minimal PHP Code Causing Issue

1. Install rector: `composer req --dev "rector/rector:2.0.3` → OK, version 2.0.3 is downloaded (I checked in `composer info` too)
2. check `vendor/bin/rector --version` returns `Rector 2.0.1`

## Expected Behaviour

The `rector --version` should return the right version, in this case `2.0.3`

**Comment by samsonasik** [comment]
It because of version resolver not updated in

https://github.com/rectorphp/rector/blob/3f27091368bd935dbbaa8387099792fb20f65f68/src/Application/VersionResolver.php#L22

It was on a rerelease on same commit on rector-src because patch in rector-downgrade-php, that's a rare use case due to major version and fast patch :)

Should be working again on next release 2.0.4 as now already different commit.
