### ISSUE TITLE
Support for property hooks

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector#8954]
# Feature Request

FYI PHPStan 2.1 is going to be released in a couple of days and is going to fully support property hooks and other PHP 8.4 features.

I just posted a community update about what custom extensions and projects like Rector should do to take advantage of property hooks analysis, so make sure to read through it and plan the progress on your side 😊 https://github.com/phpstan/phpstan/discussions/12337

Thanks and happy new year!

**Comment by samsonasik** [comment]
we handle at rector for property hook crash at PR:

- https://github.com/rectorphp/rector-src/pull/6575

If we update to PHPStan 2.1, and got virtual node unwrapped for property hook, I think we will get notified as the fixture test already exists for property hook.

Btw, it would be great if you can merge my PHPStan PR for unreachable next stmts:

- https://github.com/phpstan/phpstan-src/pull/3745

included in PHPStan 2.1 so we can uses the `->getNextStatements()` on unreachable statement node instead of custom visitor.

Regarding my PR for Printer crash on `MethodCallableNode` at PR:

- https://github.com/phpstan/phpstan-src/pull/3752

Feel free to take over as I am not familiar with PHPStan printer usage on Virtual Node.

**Comment by samsonasik** [comment]
Rector 2.0.5 released with support PHP-Parser 5.4.0 and PHPStan 2.1.0

https://github.com/rectorphp/rector/releases/tag/2.0.5
