### ISSUE TITLE
[CodeQuality] Unused foreach value

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#897]
```diff
-foreach ($entityConfig[$section]['fields'] as $key => $field) {
+foreach (array_keys($entityConfig[$section]['fields']) as $key) {
                if (in_array($key, ['imageFile', 'imageUploadedAt'], true)) {
                    unset($backendConfig['entities'][$alias][$section]['fields'][$key]);
                }
            }
```

**Comment by TomasVotruba** [comment]
@stloyd Could you elaborate on your :-1: ?

**Comment by stloyd** [comment]
For me it's something like premature optimization that in fact adds little overhead instead of giving any advantage.
With `array_keys()`: https://3v4l.org/RhjBr/vld#output
_Normal_ loop: https://3v4l.org/BrsMe/vld#output
As you can see it's more calls internally & as well `array_keys()` also loops over the array to get keys, so it's like looping twice for me instead of one just to hide usage of one variable.

**Comment by TomasVotruba** [comment]
Closing as controversial
